import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "vi";

interface DictionaryValueMap {
  [key: string]: string | string[] | DictionaryValueMap;
}
type DictionaryValue = string | string[] | DictionaryValueMap;

const dictionaries: Record<AppLanguage, Record<string, DictionaryValue>> = {
  en: {
    common: {
      language: "Language",
      english: "English",
      vietnamese: "Tiếng Việt",
      user: "User",
      save: "Save",
      cancel: "Cancel",
      settings: "Settings",
      contactUs: "Contact Us",
      helpCenter: "Help Center",
      signOut: "Sign out",
      rename: "Rename",
      renaming: "Renaming...",
      verified: "Verified",
      notVerified: "Not Verified",
      loading: "Loading...",
      active: "Active",
      locale: "en-US",
      categories: {
        math: "Math",
        english: "English",
        science: "Science",
        socialStudies: "Social Studies",
        globalLanguages: "Languages",
        general: "General",
      },
      exactly: "exactly",
      retry: "Retry",
      correct: "Correct",
      incorrect: "Incorrect",
      total: "Total",
      time: "Time",
      check: "Check",
      continue: "Continue",
      back: "Back",
      next: "Next",
      backToDashboard: "Back"
    },
    publicHeader: {
      login: "Sign in",
      signup: "Sign up",
    },
    auth: {
      verifyEmail: "Verify your email",
      codeSent: "We've sent a 6-digit code to {email}",
      enterCode: "Enter verification code",
      verify: "Verify Email",
      resendCode: "Resend code",
      codeResent: "Verification code resent!",
      invalidCode: "Invalid or expired code",
      verifying: "Verifying...",
    },
    footer: {
      about: "About",
      blog: "Blog",
      faq: "FAQ",
      contact: "Contact",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      rights: "All rights reserved.",
      madeBy: "Made with love by Gia Hien",
    },
    routeTitles: {
      home: "Home",
      create: "Create Quiz",
      feed: "Community Feed",
      dashboard: "Dashboard",
      history: "Archive",
      generate: "Generate Quiz",
      quiz: "Quiz",
      results: "Results History",
      quizResults: "Quiz Complete",
      study: "Study Mode",
      editQuiz: "Edit Quiz",
      progress: "Progress",
      inProgress: "In Progress",
      about: "About",
      contact: "Contact",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
      default: "Prepetual",
    },
    sidebar: {
      menu: "Menu",
      analysis: "Analysis",
      folders: "Folders",
      dashboard: "Dashboard",
      create: "Create",
      yourQuizzes: "Your Quizzes",
      discover: "Discover",
      progress: "Progress",
      results: "Results",
      noFolders: "No folders created",
      settings: "Settings",
      helpCenter: "Help Center",
      contactUs: "Contact Us",
      signOut: "Sign out",
      renameFolder: "Rename Folder",
      renameFolderDescription: "Enter a new name for this folder.",
      folderName: "Folder name",
      folderRenamed: "Folder renamed",
      failedRenameFolder: "Failed to rename folder",
      failedTogglePin: "Failed to toggle pin",
      pinToTop: "Pin to Top",
      unpinFromTop: "Unpin from Top",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account preferences",
      profile: "Profile",
      username: "Username",
      usernamePlaceholder: "Enter your username",
      appearance: "Appearance",
      language: "Language",
      languageDescription: "Choose how the interface is displayed.",
      light: "Light",
      dark: "Dark",
      system: "System",
      quizExperience: "Quiz Experience",
      consecutiveConfetti: "Consecutive correct confetti",
      consecutiveConfettiDescription: "Confetti after 3+ correct answers in a row",
      skipRevision: "Skip revision questions",
      skipRevisionDescription: "Go straight to results",
      privacy: "Privacy",
      autoDelete: "Auto-delete uploaded files",
      autoDeleteDescription: "Delete source files after quiz generation",
      autoDeleteWarning: "Your uploads enhance your experience by making it more personalized.",
      unsavedChanges: "Unsaved changes",
      saveSuccess: "Settings saved",
      saveSuccessDescription: "Your preferences have been updated.",
      saveError: "Failed to save settings. Please try again.",
      imageUploaded: "Image uploaded",
      imageUploadedDescription: "Your profile picture has been updated.",
      uploadFailed: "Upload failed",
      uploadFailedDescription: "Failed to upload image. Please try again.",
      invalidFileType: "Invalid file type",
      invalidFileTypeDescription: "Please upload an image file.",
      fileTooLarge: "File too large",
      fileTooLargeDescription: "Please upload an image smaller than 10MB.",
    },
    progress: {
      title: "Your Progress",
      noAttempts: "Take some quizzes to start tracking your progress.",
      reviewQuizzes: "Review quizzes",
      createQuiz: "Create a quiz",
      attempts: "attempts",
      attempt: "attempt",
      noResults: "No results yet",
      noResultsDescription: "Start with one quiz and this page will track accuracy, trends, and subject-level progress.",
      createFirstQuiz: "Create Your First Quiz",
      accuracy: "ACCURACY",
      quizzesTaken: "QUIZZES TAKEN",
      trend: "TREND",
      performanceDetails: "Performance details",
      performanceDetailsDescription: "Break down your recent scores and subject coverage.",
      overview: "Overview",
      subjects: "Subjects",
      accuracyOverTime: "Accuracy Over Time",
      accuracyOverTimeDescription: "Performance by subject across your recent quizzes.",
      scoreDistribution: "Score Distribution",
      scoreDistributionDescription: "See where most of your quiz scores are landing.",
      noSubjectData: "No subject data yet.",
      quizzesTakenCount: "{count} quizzes taken",
      quizTakenCount: "{count} quiz taken",
      active: "Active",
      average: "Average",
      bestScore: "Best Score",
      lastSessions: "{count} last sessions",
      encouragementExcellent: "You're mastering your material. Keep up the excellent work!",
      encouragementGood: "You're doing well! A little more practice will make you unstoppable.",
      encouragementFair: "You're on the right track. Consistency is the key to success!",
      encouragementPractice: "Learning takes time. Each quiz brings you closer to mastery!",
    },
    about: {
      heroTitle: "About",
      heroSubtitle: "Built on a simple belief:",
      understandingIsEverything: "understanding is everything",
      ourBelief: "Our Belief",
      beliefTitle: "Learning should be about understanding.",
      beliefSubtitle: "Not memorizing answers. Not cramming the night before. Not highlighting an entire textbook and hoping something sticks.",
      beliefHighlight: "When you truly understand a concept, you’re not just prepared for one question — you’re prepared for any question.",
      beliefDescription: "That's the idea behind Prepetual. When we understand how something works—not just what the answer is—we can apply that knowledge anywhere. A new question, a different format, a harder exam. It doesn't matter. Understanding travels with you.",
      theProblem: "The Problem",
      problemTitle: "Most study tools get it backwards",
      problemDesc1: "We kept seeing the same pattern: students spending hours copying questions into flashcard apps, formatting study guides, color-coding notes. They were doing so much work around studying, but never actually studying.",
      problemDesc2: "And even when they did quiz themselves, the questions tested recall—\"What year did X happen?\"—not understanding. You could ace the quiz and still not understand the material.",
      problemHighlight: "We wanted to build something that skips the busywork and goes straight to what matters: do you actually understand this?",
      oldWay: "The old way",
      oldWay1: "Copy questions by hand",
      oldWay2: "Format flashcards for hours",
      oldWay3: "Memorize without understanding",
      oldWay4: "Hope it sticks for the exam",
      prepetualWay: "The Prepetual way",
      prepetualWay1: "Upload your notes",
      prepetualWay2: "AI tests your understanding",
      prepetualWay3: "Learn from explanations",
      prepetualWay4: "Actually know the material",
      ourApproach: "Our Approach",
      approachTitle2: "Understanding over memorization",
      approachTitle_Thinking: "Questions that make you think",
      approachDesc_Thinking: "Prepetual's AI doesn't just pull facts from your notes and ask you to repeat them. It generates questions that test whether you truly grasp the concept—the kind of questions that make you pause, connect ideas, and reason through an answer.",
      approachTitle_Teaching: "Explanations that actually teach",
      approachDesc_Teaching: "Getting a question wrong shouldn't feel like a dead end. Every answer comes with a clear explanation—not just \"the correct answer is B,\" but why it's correct and how the concept works. That's where real learning happens.",
      approachTitle_Pip: "Pip guides, never gives away",
      approachDesc_Pip: "When you're stuck, Pip—your AI study companion—doesn't hand you the answer. It asks follow-up questions, gives hints, and walks you through the reasoning. Because the moment you figure it out yourself is the moment you truly understand it.",
      approachTitle_Revision: "Revision that targets gaps",
      approachDesc_Revision: "Prepetual remembers what you got wrong and lets you retry just those questions. Instead of reviewing everything, we focus on the concepts that haven't clicked yet—until they do.",
      ourStory: "Our Story",
      storyTitle: "Built by students, for students",
      storyDesc1: "Prepetual wasn't born in a corporate office or a startup incubator. It was built by students who were frustrated with the same problems you face every day. Late-night cram sessions that don't stick. Study tools that feel like extra homework. The nagging feeling that you're preparing for exams the wrong way.",
      storyDesc2: "We built Prepetual because we needed it ourselves. We understand what it's like to stare at a stack of notes and feel completely lost. We know the difference between memorizing something for a test and actually getting it. And we wanted a tool that bridges that gap.",
      storyHighlight: "Because when a student builds something for other students, the result isn't just functional—it's personal. Every decision we made came from our own experience in the classroom.",
      storyDesc3: "We're not a team of engineers guessing what students need. We are the students. And we're still learning, improving, and refining Prepetual alongside everyone who uses it.",
      studyCompanion: "Study Companion",
      companionTitle: "Meet Pip",
      companionDesc1: "Pip is your personal AI study companion. Available 24/7, Pip helps you understand difficult concepts without just giving away the answer.",
      companionDesc2: "Unlike a search engine that dumps information on you, Pip guides you through problems step-by-step, asks you questions to check your understanding, and celebrates when you get it right. It's the patient tutor everyone deserves.",
      companionTag1: "Hints, not answers",
      companionTag2: "Step-by-step guidance",
      companionTag3: "Never judges",
      companionTag4: "Available 24/7",
      companionDemo1: "I don't understand the difference between mitosis and meiosis. Can you help?",
      companionDemo2: "Great question! Think of it this way: both involve cell division, but they have different goals. Let me give you a hint—how many daughter cells does each process produce?",
      companionDemo3: "Mitosis makes 2 and meiosis makes 4?",
      companionDemo4: "Exactly right! Now you're getting it. That's a key difference to remember for your exam.",
      whatWeValue: "What We Value",
      valuesTitle: "Principles behind Prepetual",
      valuesSubtitle: "These aren't corporate values on a wall. They're the convictions that shaped every decision in building this tool.",
      valueTitle1: "Accessible to All",
      valueDesc1: "Education tools should be free and available to every student, everywhere. No exceptions. No premium tiers. If you can access the internet, you can use Prepetual.",
      valueTitle2: "Understanding First",
      valueDesc2: "Every feature is designed to deepen understanding, not just help you pass a test. Because a student who understands the material doesn't need to worry about the exam.",
      valueTitle3: "Privacy Matters",
      valueDesc3: "Your study data belongs to you. We don't sell it, share it, or use it for anything other than helping you learn. Your notes stay your notes.",
      valueTitle4: "Always Improving",
      valueDesc4: "We study the science of learning, listen to students, and constantly evolve Prepetual. Our goal is always the same: help you understand more, faster.",
      acrossEverySubject: "Across Every Subject",
      approachTitle: "Our approach to different subjects",
      approachDesc: "Understanding looks different in every subject. Here's how Prepetual applies our shared philosophy—understanding over memorization—across the topics you study.",
      howItWorks: "How it works in practice",
      subjects: {
        Math: {
          title: "Math",
          philosophy: "Math isn't about memorizing formulas—it's about understanding why they work. When we truly grasp the logic behind a formula, we can derive it ourselves, adapt it to new problems, and never feel lost on an exam. Prepetual generates questions that test your reasoning, not just your ability to plug in numbers.",
          example: "Instead of asking \"What is the quadratic formula?\", Prepetual might ask \"Why does completing the square lead to the quadratic formula?\" or present a problem that requires you to decide which approach to use.",
        },
        EnglishLiterature: {
          title: "English & Literature",
          philosophy: "Literature is about interpretation, context, and connecting ideas across texts. Memorizing plot summaries won't help you write a strong essay. We believe in testing your ability to analyze themes, understand character motivations, and form your own arguments backed by evidence from the text.",
          example: "Rather than \"Who is the protagonist of the novel?\", you might see \"How does the author use the setting to reflect the protagonist's internal conflict?\" Questions that push you to think critically.",
        },
        Science: {
          title: "Science",
          philosophy: "Science is built on understanding processes, not memorizing facts. If you understand how photosynthesis works at a conceptual level, you can answer any question about it—even ones you've never seen before. That's the power of understanding over memorization.",
          example: "Instead of \"Name the stages of mitosis,\" Prepetual asks \"What would happen to a cell if the spindle fibers failed to form during mitosis?\" Understanding the process means you can predict outcomes.",
        },
        SocialStudiesHistory: {
          title: "Social Studies & History",
          philosophy: "History isn't a list of dates and names—it's about understanding cause and effect, recognizing patterns, and learning from human decisions. When you understand why events happened, you can connect them to other events and see the bigger picture.",
          example: "Not \"In what year did World War I begin?\" but \"What combination of alliances and tensions made a large-scale conflict in Europe nearly inevitable by 1914?\" Understanding context makes the facts stick naturally.",
        },
        GlobalLanguages: {
          title: "Global Languages",
          philosophy: "Learning a language is about understanding how it works—grammar patterns, sentence structure, context—not just memorizing vocabulary lists. When we understand the rules, we can construct sentences we've never practiced before and communicate freely.",
          example: "Beyond \"Translate this word,\" Prepetual tests whether you can use the word correctly in context, understand why a certain tense is used, or identify the nuance between similar expressions.",
        },
        OtherSubjects: {
          title: "Other Subjects",
          philosophy: "No matter the subject—art, music, computer science, psychology—the same principle applies. Surface-level memorization fades quickly. But when you build a mental model of how something works, that knowledge becomes part of how you think. That's what Prepetual aims for, in every subject.",
          example: "Upload any study material and the AI adapts. It detects the subject, understands the content, and generates questions that challenge your comprehension—not your short-term memory.",
        },
      },
    },
    learningTips: [
      "Spaced repetition helps you remember better. Try reviewing your quizzes at increasing intervals for maximum retention.",
      "Teaching others what you've learned is one of the best ways to reinforce your own understanding.",
      "Taking breaks between study sessions helps your brain consolidate information more effectively.",
      "Active recall (testing yourself) is more effective than passive review. Keep taking those quizzes!",
      "Getting enough sleep is crucial for memory consolidation. Your brain processes what you learned while you rest.",
      "Mix up different topics in your study sessions. Interleaving subjects can improve long-term retention.",
      "Write down key concepts by hand. The physical act of writing helps cement information in memory.",
      "Create mental associations or stories to connect new information with what you already know.",
      "Study in short, focused bursts of 25-30 minutes, then take a 5-minute break. This is called the Pomodoro Technique.",
      "Challenge yourself with harder questions. Struggling a bit helps you learn more deeply.",
      "Review material right before sleep. Your brain will continue processing it overnight.",
      "Explain concepts in your own words. If you can't simplify it, you don't understand it well enough yet.",
      "Stay hydrated and maintain good nutrition. Your brain needs proper fuel to learn effectively.",
      "Test yourself before you think you're ready. Making mistakes early helps identify gaps in your knowledge.",
      "Connect new concepts to real-world examples. Practical applications make abstract ideas stick better.",
      "When doing multiple-choice questions, don't just find the right answer. Explain to yourself why the other three options are wrong. This triples your learning from a single question.",
      "Upload your material and take a quiz before you start intensive studying. This 'pre-test' highlights exactly which parts of the PDF you already know and which parts need your full attention.",
    ],
    home: {
      hero: {
        makeYourMaterials: "Make your materials",
        talkBack: "talk back",
        subtitle: "Let every definition respond to you. Stay connected to what you learn.",
        getStarted: "Get Started",
        itsFree: "—it's free",
        howItWorks: "How It Works",
        freeForever: "Free forever",
        noCreditCard: "No credit card",
        fileFormats: "PDF, Word, Images",
      },
      stats: {
        freeForever: "Free Forever",
        fileFormats: "File Formats",
        unlimitedQuizzes: "Unlimited Quizzes",
      },
      howItWorks: {
        badge: "Simple Process",
        title: "How It Works",
        subtitle: "From notes to quizzes in just a few clicks",
        steps: {
          upload: {
            title: "Step 1: Upload",
            label: "Upload",
            desc: "Drop your study materials — PDFs, images, Word docs, or PowerPoint files. We handle the rest.",
            clickToUpload: "Click to upload",
            orDragDrop: "or drag & drop files",
          },
          extract: {
            title: "Step 2: Extract",
            label: "Extract",
            desc: "Our AI reads and understands your content with high precision — text, diagrams, and tables included.",
            parsing: "Parsing document...",
            extracting: "Extracting key concepts...",
            identifying: "Identifying relationships...",
            complete: "complete",
            advanced: "Advanced Extraction",
            fidelity: "Omission-free high-fidelity parsing",
          },
          generate: {
            title: "Step 3: Generate",
            label: "Generate",
            desc: "Smart AI creates diverse, personalized quiz questions from your material — instantly.",
            mcq: "Multiple Choice",
            tf: "True / False",
            short: "Short Answer",
            q1: "What is the primary function of mitochondria?",
            q2: "DNA replication occurs in the G1 phase.",
            q3: "Define the term 'Osmosis' in your own words.",
            architecting: "AI Architecting...",
          },
          learn: {
            title: "Step 4: Learn",
            label: "Learn",
            desc: "Master every topic with interactive quizzes, flashcards, and spaced repetition.",
            expert: "Expert Proficiency",
            mastery: "Mastery Progress",
            fastTracking: "Fast tracking",
            startQuiz: "Start Quiz",
            study: "Study",
          },
        },
      },
      parsing: {
        badge: "Import your own questions",
        title: "Your context, exactly as it is.",
        subtitle: "Upload any exam or worksheet. We intelligently extract every question, word-for-word.",
        original: "Original Document",
        interactive: "Interactive Quiz",
        converting: "Converting...",
        ready: "Ready",
      },
      features: {
        badge: "Everything You Need",
        title: "Power your potential with AI",
        subtitle: "From raw notes to interactive study sessions in seconds.",
        createFirstQuiz: "Create Your First Quiz",
        dropNotes: "Drop your notes or a textbook page to begin.",
        continueToGenerate: "Continue to Generate",
        startHere: "Start Here",
        aiGen: {
          title: "AI Quiz Generation",
          desc: "Our AI analyzes your content to generate diverse question types that test comprehension.",
        },
        multiFormat: {
          title: "Multi-Format Support",
          desc: "PDFs, textbook photos, docs, and images.",
        },
        progress: {
          title: "Progress Tracking",
          desc: "Visual insights into your learning journey.",
        },
        studyMode: {
          title: "Smart Study Mode",
          desc: "Interactive flashcards that adapt to you.",
        },
        pip: {
          title: "Meet Pip, Your AI Buddy",
          desc: "Pip provides hints and explains concepts when you're stuck on a question.",
        },
        spaced: {
          title: "Spaced Repetition",
          desc: "Retry missed questions until you master them.",
        },
      },
      cta: {
        badge: "Start your journey today",
        title1: "Master your materials.",
        title2: "Elevate your performance.",
        desc: "Join thousands of students who have transformed how they study with AI-powered personalized practice.",
        getStartedFree: "Get Started Free",
        learnMore: "Learn More",
      },
      demo: {
        mitochondriaQ: "What is the primary function of mitochondria in a cell?",
        energyProduction: "Energy production",
        proteinSynthesis: "Protein synthesis",
        cellDivision: "Cell division",
        wasteRemoval: "Waste removal",
        correct: "Correct!",
        mitochondriaExp: "Mitochondria are known as the powerhouse of the cell, producing ATP through cellular respiration.",
        revealHint: "Click & hold to reveal",
      },
    },
    dashboard: {
      welcomeBack: "Welcome back",
      learningDashboard: "Your Learning Dashboard",
      continueWhereLeftOff: "Continue where you left off or create something new.",
      createFirstQuiz: "Let's create your first quiz and start learning.",
      continueLearning: "Continue Learning",
      viewAllInProgress: "View all in progress",
      recentQuizzes: "Recent Quizzes",
      viewAll: "View all",
      yourStats: "Your Stats",
      created: "CREATED",
      questions: "QUESTIONS",
      accuracy: "ACCURACY",
      quickActions: "Quick Actions",
      createNewQuiz: "Create New Quiz",
      aiPoweredGeneration: "AI-powered generation",
      continueStudy: "Continue Study",
      learningTip: "Learning Tip",
      deleteQuizProgress: "Delete Quiz Progress?",
      revisingWarning: "You're currently revising this quiz. Deleting will remove all your progress including your original answers and revision progress.",
      keepRevising: "Keep Revising",
      deleteAllProgress: "Delete All Progress",
    },
    create: {
      title: "Create a Practice Quiz",
      subtitle: "How would you like to add your learning material today?",
      uploadDocs: "Upload Documents",
      uploadDocsDesc: "Upload your PDFs, class notes, or textbook photos",
      pasteNotes: "Paste Study Notes",
      pasteNotesDesc: "Copy and paste your digital notes or summaries",
      learnYoutube: "Learn from YouTube",
      learnYoutubeDesc: "Turn any educational video into a practice test",
      materialReady: "Study Material Ready",
      pagesAdded: "{count} pages added and ready for Pip to review",
      wordsAdded: "{count} words added from your {source}",
      removeMaterial: "Remove study material?",
      removeMaterialDesc: "This will clear your current notes. You'll need to re-upload or re-paste to continue.",
      confirmRemoval: "Confirm Removal",
      formats: {
        docs: "PDF / DOCX",
        photos: "Photo of notes",
        handwritten: "Handwritten notes",
        summaries: "Typed summaries",
        lectures: "Video lectures",
        explainers: "Short explainers",
      },
      wordsCount: "{count} Words",
      visualAssetsFound: "Visual Assets Found",
      preview: "Preview",
      generateQuestions: "Generate Questions",
      addStudyMaterials: "Add Study Materials",
      fileSizeLimit: "File size up to 10MB",
      pastePlaceholder: "Paste your study material here... (AI thrives on detail, give it at least 50 characters)",
      readyToQuiz: "Ready to Quiz",
      validationError: "Deeper content results in better quizzes. Please provide at least 50 characters.",
      youtubeLink: "Drop a YouTube link below and we'll extract its core knowledge for your quiz.",
      youtubePlaceholder: "https://www.youtube.com/watch?v=...",
      learningFromVideo: "Learning from video...",
      prepareQuiz: "Prepare Quiz",
      compatibility: "Compatibility: Watch or Short links",
      youtubeVideo: "YouTube video",
      pastedText: "pasted text",
      image: "image",
      document: "document",
    },
    feed: {
      discover: "Discover",
      exploreCommunity: "Explore quizzes shared by the prepetual community",
      searchQuizzes: "Search quizzes...",
      totalQuizzes: "quizzes",
      totalQuestions: "questions",
      totalCreators: "creators",
      recommendedForYou: "Recommended for You",
      basedOnHistory: "Based on your learning history",
      noQuizzesFound: "No quizzes found",
      tryDifferentSearch: "Try a different search term",
      clearFilters: "Clear Filters",
      noQuizzesYet: "No quizzes yet",
      beFirstToShare: "Be the first to share your knowledge with the community!",
      featured: "Featured",
      popularQuizzes: "Popular quizzes from the community",
      allQuizzes: "All Quizzes",
      recentQuizzes: "Recent Quizzes",
      moreQuizzesToExplore: "{count} more quizzes to explore",
      quizzesAvailable: "{count} quizzes available",
      play: "Play",
      takeQuiz: "Take Quiz",
      study: "Study",
      curated: "Curated",
      forYou: "For You",
      practiceMore: "Practice More",
      quizCreator: "Quiz Creator",
    },
    history: {
      title: "Library",
      savedQuizzes: "{count} quizzes saved",
      savedQuiz: "{count} quiz saved",
      noQuizzesSaved: "Your saved quizzes will appear here",
      newQuiz: "New Quiz",
      quizzes: "Quizzes",
      folders: "Folders",
      noQuizzesYet: "No quizzes yet",
      createFirstQuiz: "Create your first quiz to get started",
      createQuiz: "Create Quiz",
      searchLibrary: "Search your library...",
      allSubjects: "All Subjects",
      noMatchingQuizzes: "No matching quizzes found in your library.",
      clearFilters: "Clear all filters",
      questions: "{count} questions",
      review: "Review",
      take: "Take",
      editQuiz: "Edit Quiz",
      draftMode: "Draft Mode",
      publishToLibrary: "Publish to Library",
      copyShareLink: "Copy Share Link",
      permanentlyDelete: "Permanently Delete",
      collectionManager: "Collection Manager",
      organizeDesc: "Organize your personal practice library into subjects.",
      createFolder: "Create Folder",
      stayOrganized: "Stay organized",
      groupQuizzesDesc: "Group your quizzes by class, exam, or topic for faster access.",
      quiz: "quiz",
      quizzesCount: "quizzes",
      unpinFromTop: "Unpin from Top",
      pinToTop: "Pin to Top",
      renameFolder: "Rename Folder",
      deleteCollection: "Delete Collection",
      deleteQuiz: "Delete Quiz",
      deleteQuizConfirm: "Are you sure you want to delete \"{title}\"? This action cannot be undone.",
      deleteFolderConfirm: "Are you sure you want to delete \"{name}\"? Quizzes inside won't be deleted, they'll just become unfiled.",
      archive: "Archive",
      addQuizzes: "Add Quizzes",
      folderNotFound: "Folder not found",
      folderNotFoundDesc: "This folder may have been deleted.",
      backToArchive: "Back to Archive",
      removeFromFolder: "Remove from Folder",
      noQuizzesInFolderDesc: "Add existing quizzes or create new ones to organize here",
      addQuizzesToFolder: "Add Quizzes to Folder",
      selectQuizzesForFolder: "Select quizzes to include in \"{name}\"",
      quizzesUpdated: "Quizzes updated",
      quizRemovedFromFolder: "Quiz removed from folder",
      failedToRemoveQuiz: "Failed to remove quiz",
      rename: "Rename",
      save: "Save",
      questionsCount: "{count} questions",
      quizDeleted: "Quiz deleted",
      quizDeletedDesc: "The quiz has been removed from your history.",
      error: "Error",
      failedDeleteQuiz: "Failed to delete quiz",
      quizShared: "Quiz shared",
      quizHidden: "Quiz hidden",
      quizSharedDesc: "Your quiz is now visible in the community feed.",
      quizHiddenDesc: "Your quiz is now private.",
      failedUpdateVisibility: "Failed to update quiz visibility",
      folderCreated: "Folder created",
      failedCreateFolder: "Failed to create folder",
      folderRenamed: "Folder renamed",
      failedRenameFolder: "Failed to rename folder",
      folderDeleted: "Folder deleted",
      failedDeleteFolder: "Failed to delete folder",
      failedTogglePin: "Failed to toggle pin",
      linkCopied: "Link copied!",
      linkCopiedDesc: "Share this link with others to let them take the quiz.",
    },
    inProgress: {
      title: "In Progress",
      loadingProgress: "Loading your saved sessions...",
      sessionsWaiting: "{count} quiz sessions waiting to be completed",
      sessionWaiting: "{count} quiz session waiting to be completed",
      allCaughtUp: "All caught up — no sessions in progress",
      sessionsCount: "{count} sessions",
      sessionCount: "{count} session",
      loadingProgressEllipsis: "Loading your progress...",
      allCaughtUpTitle: "All caught up!",
      noInProgressDesc: "You don't have any quizzes in progress. Start a quiz and save your progress to pick up right where you left off.",
      browseQuizzes: "Browse your quizzes",
      revising: "Revising",
      questionsLeftToReview: "{count} questions left to review",
      questionLeftToReview: "{count} question left to review",
      answeredOfTotal: "{answered} of {total} answered",
      questionsTotal: "{count} questions total",
      continueReview: "Continue Review",
      continueQuiz: "Continue Quiz",
      discardProgress: "Discard progress?",
      discardProgressRevisingDesc: "This will permanently delete all your progress for \"{title}\", including your original answers and revision progress.",
      discardProgressDesc: "This will discard your saved progress for \"{title}\". You can retake it from scratch.",
      keepIt: "Keep it",
      discard: "Discard",
      timeSpent: "{time} spent",
      ago: "{time} ago",
    },
    study: {
      noQuizSelected: "No quiz selected",
      noQuizSelectedDesc: "Select a quiz from your history to start mastering it with flashcards.",
      goHistory: "Go to History",
      multipleChoice: "Multiple Choice",
      trueFalse: "True / False",
      shortAnswer: "Short Answer",
      sessionComplete: "Study Session Complete!",
      sessionCompleteDesc: "Amazing progress on \"{title}\"",
      mastered: "Mastered",
      stillLearning: "Still Learning",
      retakeCards: "Retake Cards",
      returnDashboard: "Return to Dashboard",
      flashcardSession: "Flashcard Session",
      progress: "Progress: {current} / {total}",
      question: "Question",
      tapToReveal: "Tap to reveal answer",
      correctAnswer: "Correct Answer",
      explanation: "Explanation",
      swipeToGrade: "Swipe left or right to grade",
      learning: "Learning",
      swipeArrowNav: "Swipe or use Arrow Keys to navigate",
    },
    results: {
      title: "Results History",
      subtitle: "Review all your past quiz attempts and track your progress.",
      totalAttempts: "{count} Total Attempts",
      noResultsYet: "No results yet",
      noResultsDesc: "Take your first quiz to see your performance results and detailed history here.",
      createQuiz: "Create a Quiz",
      searchPlaceholder: "Search quizzes by title...",
      allSubjects: "All Subjects",
      noResultsMatching: "No results found matching your filters.",
      clearFilters: "Clear all filters",
      revisionAvailable: "Revision Available",
      correct: "correct",
      attempts: "{count} attempts",
      best: "Best: {score}%",
      revise: "Revise",
      bestLabel: "Best",
      correctCount: "{correct}/{total} correct",
      attemptsCount: "{count} attempts",
      smartReviewGenerated: "Smart Review Generated",
      smartReviewDesc: "Focusing on your most frequent mistakes + similar challenges.",
      reviewFailed: "Review Failed",
      reviewFailedDesc: "Could not generate your review session. Please try again.",
    },
    quizResults: {
      scoreMessages: {
        90: "Excellent work — you're mastering this.",
        80: "Great job — you're very close.",
        70: "Nice progress — keep practicing.",
        60: "Good start — review and try again.",
        default: "Keep going — practice makes progress.",
      },
      quizSessionSummary: "{correct}/{total} correct",
      reviewSessionSummary: "{correct}/{total} fixed in review",
      fixed: "Fixed",
      needsWork: "Needs work",
      reviewAnswers: "Review answers",
      yourAnswer: "Your answer",
      noAnswerProvided: "No answer provided",
      correctAnswer: "Correct answer",
      whyThisWasWrong: "Why this was wrong",
      signUpToSeeExplanations: "Sign in to see detailed explanations.",
      unlockFullFeatures: "Unlock full features",
      unlockFullFeaturesDesc: "Create an account to save results, track progress, and get smarter reviews.",
      alreadyHaveAccount: "Already have an account?",
      retakeQuiz: "Retake quiz",
    },
    quizComplete: {
      quizComplete: "Quiz Complete!",
      quizCompleteDesc: "Great work — here are your results.",
      reviewSessionComplete: "Review Session Complete!",
      reviewSessionCompleteDesc: "Nice review — here are your results.",
    },
    revisionSummary: {
      greatPractice: "Great Practice!",
      buildingMemories: "You're building stronger memories with every revision.",
      questionsMastered: "questions mastered in this session",
      retryCount: "including {count} you got right on retry",
      weeklyRevisedCount: "questions revised this week",
      mistakesLockDesc: "Mistakes are how memories get locked in. Keep revisiting and watch them disappear.",
    },
    generate: {
      goBack: "Go Back",
      materialProcessed: "Material Processed & Ready",
      title: "Customize Your Practice",
      subtitle: "Set your preferences and let Prepetual build the perfect quiz for you.",
    },
    quiz: {
      back: "Back",
    },
    quizGenerator: {
      yourStudyMaterial: "Your Study Material",
      imagesReady: "{count} images ready for AI analysis",
      imageReady: "{count} image ready for AI analysis",
      clickToInspect: "Click to inspect pages",
      viewExtractedText: "View extracted text",
      charactersReady: "{count} characters ready for quiz generation",
      collapse: "Collapse",
      expandFullText: "Expand Full Text",
      viewImages: "View images",
      smartPractice: "Smart Practice",
      smartPracticeDesc: "Prepetual creates original questions based on your specific notes.",
      importQuestions: "Import Questions",
      importQuestionsDesc: "Already have an exam? Prepetual can scan it and find the answers.",
      numQuestions: "Number of Questions",
      chooseQuestions: "Choose between 3-{max} questions",
      difficultyLevel: "Difficulty Level",
      howChallenging: "How challenging should the quiz be?",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      questionTypes: "Question Types",
      selectOneOrMore: "Select one or more types",
      multipleChoice: "Multiple Choice",
      multipleChoiceDesc: "A, B, C or D",
      trueFalse: "True / False",
      true: "True",
      false: "False",
      trueFalseDesc: "True or False questions",
      shortAnswer: "Short Answer",
      shortAnswerDesc: "Write it out",
      preparePracticeQuiz: "Prepare Practice Quiz",
      smartImport: "Smart Import",
      smartImportDesc: "Already have a test? Prepetual will scan it, recognize the questions, and verify the correct answers for you.",
      perfectFor: "Perfect For",
      quizPapers: "Quiz Papers",
      worksheets: "Worksheets",
      importPracticeQuiz: "Import Practice Quiz",
    },
    quizPlayer: {
      excellentWork: "Excellent work!",
      nailedIt: "You nailed it!",
      brilliant: "Brilliant!",
      keepItUp: "Keep it up!",
      perfect: "Perfect!",
      outstanding: "Outstanding!",
      onFire: "You're on fire!",
      impressive: "Impressive!",
      improvement: "Look at that improvement!",
      learnedLastOne: "You learned from the last one! Amazing!",
      secondCharm: "Second time's the charm! Great job!",
      masteredNow: "You've mastered this now!",
      growthMindset: "Growth mindset in action!",
      persistencePays: "Persistence pays off! Well done!",
      didntGiveUp: "You didn't give up and it shows!",
      howYouLearn: "That's how you learn! Fantastic!",
      dontWorry: "Don't worry, keep learning!",
      getNextOne: "You'll get the next one!",
      learningInProgress: "Learning in progress!",
      everyMistake: "Every mistake is a lesson!",
      stayCurious: "Stay curious!",
      streak2: "2 in a row!",
      streak3: "3 in a row! Nice!",
      streak4: "4 in a row! Amazing!",
      streak5: "5+ streak! Unstoppable!",
      doingGreat: "You're doing great!",
      keepGoing: "Don't worry, keep going!",
      reportSubmitted: "Report submitted",
      reportSubmittedDesc: "Thank you for your feedback! We'll look into this question.",
      reportError: "Error",
      reportErrorDesc: "Failed to submit report. Please try again later.",
      multipleChoice: "Multiple Choice",
      trueFalse: "True/False",
      shortAnswer: "Short Answer",
      question: "Question",
      correctAnswer: "Correct Answer",
      explanation: "Explanation",
      grade: "Grade",
      check: "Check",
      next: "Next",
      previous: "Previous",
      finish: "Finish",
      saveProgress: "Save Progress",
      reportBug: "Report Bug",
      grading: "Grading...",
      yourAnswer: "Your Answer",
      typeYourAnswer: "Type your answer here...",
      shortAnswerFallbackCorrect: "Your answer matches the expected answer.",
      shortAnswerFallbackIncorrect: "The expected answer was: {expected}",
      submitFailed: "Failed to submit quiz. Please try again.",
      reportFailed: "Failed to submit report. Please try again later.",
      imagesCount: "Image {current} of {total}",
      questionNumber: "Question {number}",
      partiallyCorrect: "Partially correct",
      aiAssessment: "AI Assessment",
      viewExplanation: "View Explanation",
      explain: "Explain",
      shortAnswerPlaceholder: "Type your answer here...",
      gradingInProgress: "Pip is carefully grading your answer...",
      gradingInProgressShort: "Grading...",
      jumpToQuestion: "Jump to Question",
      giveItAnotherTry: "Give it another try!",
      somethingWrong: "Something wrong?",
      reportProblem: "Report a Problem",
      reportProblemDesc: "Is there something wrong with this question? Let us know and we'll fix it.",
      whatIsIssue: "What is the issue?",
      reportReasons: {
        correct_answer_is_wrong: "Correct answer is wrong",
        explanation_is_incorrect: "Explanation is incorrect",
        typo_or_formatting_issue: "Typo or formatting issue",
        question_is_unclear: "Question is unclear",
        other: "Other"
      },
      detailsOptional: "Details (optional)",
      describeProblem: "Describe the problem in more detail...",
      submitting: "Submitting...",
      submitReport: "Submit Report",
      studyMaterial: "Study Material",
      material: "Material",
      hideTimer: "Hide timer",
      showTimer: "Show timer",
      askPip: "Ask Pip",
      results: "Results",
    }
  },
  vi: {
    common: {
      language: "Ngôn ngữ",
      english: "English",
      vietnamese: "Tiếng Việt",
      user: "Người dùng",
      save: "Lưu",
      cancel: "Hủy",
      settings: "Cài đặt",
      contactUs: "Liên hệ",
      helpCenter: "Trung tâm trợ giúp",
      signOut: "Đăng xuất",
      rename: "Đổi tên",
      renaming: "Đang đổi tên...",
      verified: "Đã xác minh",
      notVerified: "Chưa xác minh",
      loading: "Đang tải...",
      active: "Đang hoạt động",
      locale: "vi-VN",
      categories: {
        math: "Toán học",
        english: "Tiếng Anh",
        science: "Khoa học",
        socialStudies: "Khoa học xã hội",
        globalLanguages: "Ngôn ngữ",
        general: "Tổng hợp",
      },
      exactly: "chính xác",
      retry: "Thử lại",
      correct: "Chính xác",
      incorrect: "Chưa chính xác",
      total: "Tổng",
      time: "Thời gian",
      check: "Kiểm tra",
      continue: "Tiếp tục",
      back: "Quay lại",
      next: "Kế tiếp",
    },
    publicHeader: {
      login: "Đăng nhập",
      signup: "Đăng ký",
    },
    auth: {
      verifyEmail: "Xác minh email",
      codeSent: "Chúng tôi đã gửi mã 6 số đến {email}",
      enterCode: "Nhập mã xác minh",
      verify: "Xác minh Email",
      resendCode: "Gửi lại mã",
      codeResent: "Đã gửi lại mã xác minh!",
      invalidCode: "Mã không hợp lệ hoặc đã hết hạn",
      verifying: "Đang xác minh...",
    },
    footer: {
      about: "Giới thiệu",
      blog: "Blog",
      faq: "Câu hỏi thường gặp",
      contact: "Liên hệ",
      privacy: "Chính sách riêng tư",
      terms: "Điều khoản dịch vụ",
      rights: "Đã đăng ký bản quyền.",
      madeBy: "Được tạo bởi Gia Hien",
    },
    routeTitles: {
      home: "Trang chủ",
      create: "Tạo quiz",
      feed: "Cộng đồng",
      dashboard: "Bảng điều khiển",
      history: "Thư viện",
      generate: "Tạo quiz",
      quiz: "Quiz",
      results: "Lịch sử kết quả",
      quizResults: "Hoàn thành quiz",
      study: "Chế độ học",
      editQuiz: "Chỉnh sửa quiz",
      progress: "Tiến độ",
      inProgress: "Đang làm",
      about: "Giới thiệu",
      contact: "Liên hệ",
      terms: "Điều khoản dịch vụ",
      privacy: "Chính sách riêng tư",
      default: "Prepetual",
    },
    sidebar: {
      menu: "Menu",
      analysis: "Phân tích",
      folders: "Thư mục",
      dashboard: "Bảng điều khiển",
      create: "Tạo mới",
      yourQuizzes: "Quiz của bạn",
      discover: "Khám phá",
      progress: "Tiến độ",
      results: "Kết quả",
      noFolders: "Chưa có thư mục nào",
      settings: "Cài đặt",
      helpCenter: "Trung tâm trợ giúp",
      contactUs: "Liên hệ",
      signOut: "Đăng xuất",
      renameFolder: "Đổi tên thư mục",
      renameFolderDescription: "Nhập tên mới cho thư mục này.",
      folderName: "Tên thư mục",
      folderRenamed: "Đã đổi tên thư mục",
      failedRenameFolder: "Không thể đổi tên thư mục",
      failedTogglePin: "Không thể ghim hoặc bỏ ghim",
      pinToTop: "Ghim lên đầu",
      unpinFromTop: "Bỏ ghim khỏi đầu",
    },
    settings: {
      title: "Cài đặt",
      subtitle: "Quản lý tùy chọn tài khoản của bạn",
      profile: "Hồ sơ",
      username: "Tên người dùng",
      usernamePlaceholder: "Nhập tên người dùng",
      appearance: "Giao diện",
      language: "Ngôn ngữ",
      languageDescription: "Chọn ngôn ngữ hiển thị cho giao diện.",
      light: "Sáng",
      dark: "Tối",
      system: "Theo hệ thống",
      quizExperience: "Trải nghiệm làm quiz",
      consecutiveConfetti: "Pháo giấy khi trả lời đúng liên tiếp",
      consecutiveConfettiDescription: "Hiển thị pháo giấy sau 3 câu đúng liên tiếp",
      skipRevision: "Bỏ qua câu ôn tập",
      skipRevisionDescription: "Đi thẳng đến kết quả",
      privacy: "Quyền riêng tư",
      autoDelete: "Tự động xóa tệp đã tải lên",
      autoDeleteDescription: "Xóa tệp nguồn sau khi tạo quiz",
      autoDeleteWarning: "Các tệp tải lên giúp trải nghiệm học tập của bạn được cá nhân hóa hơn.",
      unsavedChanges: "Có thay đổi chưa lưu",
      saveSuccess: "Đã lưu cài đặt",
      saveSuccessDescription: "Tùy chọn của bạn đã được cập nhật.",
      saveError: "Không thể lưu cài đặt. Vui lòng thử lại.",
      imageUploaded: "Đã tải ảnh lên",
      imageUploadedDescription: "Ảnh đại diện của bạn đã được cập nhật.",
      uploadFailed: "Tải ảnh thất bại",
      uploadFailedDescription: "Không thể tải ảnh lên. Vui lòng thử lại.",
      invalidFileType: "Loại tệp không hợp lệ",
      invalidFileTypeDescription: "Vui lòng tải lên tệp hình ảnh.",
      fileTooLarge: "Tệp quá lớn",
      fileTooLargeDescription: "Vui lòng tải lên ảnh nhỏ hơn 10MB.",
    },
    progress: {
      title: "Tiến độ của bạn",
      noAttempts: "Hãy làm một vài bài quiz để bắt đầu theo dõi tiến độ.",
      reviewQuizzes: "Xem lại quiz",
      createQuiz: "Tạo quiz",
      attempts: "lượt làm",
      attempt: "lượt làm",
      noResults: "Chưa có kết quả",
      noResultsDescription: "Bắt đầu với một bài quiz và trang này sẽ theo dõi độ chính xác, xu hướng và tiến độ theo môn học.",
      createFirstQuiz: "Tạo quiz đầu tiên",
      accuracy: "ĐỘ CHÍNH XÁC",
      quizzesTaken: "SỐ QUIZ ĐÃ LÀM",
      trend: "XU HƯỚNG",
      performanceDetails: "Chi tiết hiệu suất",
      performanceDetailsDescription: "Xem điểm số gần đây và mức độ bao phủ theo môn học.",
      overview: "Tổng quan",
      subjects: "Môn học",
      accuracyOverTime: "Độ chính xác theo thời gian",
      accuracyOverTimeDescription: "Hiệu suất theo môn học trong các bài quiz gần đây.",
      scoreDistribution: "Phân bố điểm số",
      scoreDistributionDescription: "Xem phần lớn điểm số của bạn đang nằm ở khoảng nào.",
      noSubjectData: "Chưa có dữ liệu môn học.",
      quizzesTakenCount: "{count} bài quiz đã làm",
      quizTakenCount: "{count} bài quiz đã làm",
      active: "Đang hoạt động",
      average: "Trung bình",
      bestScore: "Điểm cao nhất",
      lastSessions: "{count} lượt gần nhất",
      encouragementExcellent: "Bạn đang nắm rất chắc kiến thức. Hãy tiếp tục duy trì phong độ này.",
      encouragementGood: "Bạn đang tiến bộ tốt. Chỉ cần luyện tập thêm một chút nữa.",
      encouragementFair: "Bạn đang đi đúng hướng. Sự đều đặn sẽ tạo nên khác biệt.",
      encouragementPractice: "Việc học cần thời gian. Mỗi bài quiz đều giúp bạn tiến gần hơn đến mục tiêu.",
    },
    about: {
      heroTitle: "Về",
      heroSubtitle: "Được xây dựng trên một niềm tin đơn giản:",
      understandingIsEverything: "hiểu là tất cả",
      ourBelief: "Niềm tin của chúng tôi",
      beliefTitle: "Học tập nên là về sự thấu hiểu.",
      beliefSubtitle: "Không phải là ghi nhớ câu trả lời. Không phải là học nhồi nhét trước đêm thi. Không phải là tô đậm cả cuốn sách giáo khoa và hy vọng điều gì đó sẽ đọng lại.",
      beliefHighlight: "Khi bạn thực sự hiểu một khái niệm, bạn không chỉ sẵn sàng cho một câu hỏi — bạn đã sẵn sàng cho mọi câu hỏi.",
      beliefDescription: "Đó là ý tưởng đằng sau Prepetual. Khi chúng ta hiểu cách một thứ gì đó hoạt động—không chỉ câu trả lời là gì—chúng ta có thể áp dụng kiến thức đó ở bất cứ đâu. Một câu hỏi mới, một định dạng khác, một kỳ thi khó hơn. Điều đó không quan trọng. Sự thấu hiểu sẽ luôn đi cùng bạn.",
      theProblem: "Vấn đề",
      problemTitle: "Hầu hết các công cụ học tập đều đi ngược lại",
      problemDesc1: "Chúng tôi liên tục thấy cùng một khuôn mẫu: học sinh dành hàng giờ để chép câu hỏi vào các ứng dụng flashcard, định dạng hướng dẫn học tập, đánh dấu màu cho các ghi chú. Họ đang làm quá nhiều việc xoay quanh việc học, nhưng chưa bao giờ thực sự học.",
      problemDesc2: "Và ngay cả khi họ tự kiểm tra, các câu hỏi thường chỉ kiểm tra khả năng ghi nhớ—\"X xảy ra vào năm nào?\"—chứ không phải sự thấu hiểu. Bạn có thể đạt điểm tuyệt đối nhưng vẫn không hiểu bản chất vấn đề.",
      problemHighlight: "Chúng tôi muốn xây dựng một thứ gì đó bỏ qua những công việc rườm rà và đi thẳng vào điều quan trọng: bạn có thực sự hiểu điều này không?",
      oldWay: "Cách cũ",
      oldWay1: "Chép câu hỏi bằng tay",
      oldWay2: "Định dạng flashcard hàng giờ",
      oldWay3: "Ghi nhớ mà không hiểu",
      oldWay4: "Hy vọng nó sẽ đọng lại cho kỳ thi",
      prepetualWay: "Cách của Prepetual",
      prepetualWay1: "Tải lên ghi chú của bạn",
      prepetualWay2: "AI kiểm tra sự thấu hiểu của bạn",
      prepetualWay3: "Học từ các lời giải thích",
      prepetualWay4: "Thực sự nắm vững kiến thức",
      ourApproach: "Cách tiếp cận của chúng tôi",
      approachTitle2: "Thấu hiểu thay vì ghi nhớ",
      approachTitle_Thinking: "Câu hỏi khiến bạn phải suy nghĩ",
      approachDesc_Thinking: "AI của Prepetual không chỉ lấy các sự kiện từ ghi chú của bạn và yêu cầu bạn lặp lại chúng. Nó tạo ra các câu hỏi kiểm tra xem bạn có thực sự nắm vững khái niệm hay không—loại câu hỏi khiến bạn phải dừng lại, kết nối các ý tưởng và suy luận để tìm ra câu trả lời.",
      approachTitle_Teaching: "Lời giải thích thực sự giảng dạy",
      approachDesc_Teaching: "Trả lời sai một câu hỏi không nên là một ngõ cụt. Mọi câu trả lời đều đi kèm với một lời giải thích rõ ràng—không chỉ là \"đáp án đúng là B,\" mà là tại sao nó đúng và khái niệm đó hoạt động như thế nào. Đó là nơi việc học thực sự diễn ra.",
      approachTitle_Pip: "Pip hướng dẫn, không bao giờ cho sẵn đáp án",
      approachDesc_Pip: "Khi bạn gặp khó khăn, Pip—người bạn đồng hành học tập AI của bạn—không đưa cho bạn câu trả lời. Nó đưa ra các câu hỏi tiếp theo, gợi ý và hướng dẫn bạn vượt qua các suy luận. Bởi vì khoảnh khắc bạn tự mình tìm ra nó là khoảnh khắc bạn thực sự hiểu nó.",
      approachTitle_Revision: "Ôn tập tập trung vào các lỗ hổng",
      approachDesc_Revision: "Prepetual ghi nhớ những gì bạn đã làm sai và cho phép bạn thử lại chỉ những câu hỏi đó. Thay vì xem lại tất cả, chúng tôi tập trung vào các khái niệm chưa được thông suốt—cho đến khi bạn nắm vững chúng.",
      ourStory: "Câu chuyện của chúng tôi",
      storyTitle: "Được xây dựng bởi học sinh, cho học sinh",
      storyDesc1: "Prepetual không được sinh ra trong một văn phòng tập đoàn hay một trung tâm khởi nghiệp. Nó được xây dựng bởi những học sinh từng nản lòng với chính những vấn đề mà bạn đối mặt hàng ngày. Những buổi học nhồi nhét đêm khuya không hiệu quả. Những công cụ học tập mang lại cảm giác như bài tập về nhà thêm. Cảm giác lo lắng rằng bạn đang chuẩn bị cho kỳ thi sai cách.",
      storyDesc2: "Chúng tôi xây dựng Prepetual vì chính chúng tôi cần nó. Chúng tôi hiểu cảm giác khi nhìn vào một xấp ghi chú và cảm thấy hoàn toàn lạc lõng. Chúng tôi biết sự khác biệt giữa việc ghi nhớ thứ gì đó cho một bài kiểm tra và việc thực sự hiểu nó. Và chúng tôi muốn một công cụ thu hẹp khoảng cách đó.",
      storyHighlight: "Bởi vì khi một học sinh xây dựng thứ gì đó cho những học sinh khác, kết quả không chỉ là chức năng—mà là sự thấu cảm. Mọi quyết định chúng tôi đưa ra đều đến từ chính kinh nghiệm của chúng tôi trong lớp học.",
      storyDesc3: "Chúng tôi không phải là một nhóm kỹ sư đang đoán xem học sinh cần gì. Chúng tôi chính là học sinh. Và chúng tôi vẫn đang học hỏi, cải thiện và hoàn thiện Prepetual cùng với tất cả những người sử dụng nó.",
      studyCompanion: "Bạn đồng hành học tập",
      companionTitle: "Gặp gỡ Pip",
      companionDesc1: "Pip là người bạn đồng hành học tập AI cá nhân của bạn. Sẵn sàng 24/7, Pip giúp bạn hiểu các khái niệm khó mà không chỉ đơn giản là đưa ra câu trả lời.",
      companionDesc2: "Không giống như một công cụ tìm kiếm đổ dồn thông tin lên bạn, Pip hướng dẫn bạn giải quyết các vấn đề từng bước một, đưa ra các câu hỏi để kiểm tra sự thấu hiểu của bạn và chúc mừng khi bạn làm đúng. Đó là người thầy kiên nhẫn mà mọi người đều xứng đáng có.",
      companionTag1: "Gợi ý, không cho đáp án",
      companionTag2: "Hướng dẫn từng bước",
      companionTag3: "Không bao giờ phán xét",
      companionTag4: "Sẵn sàng 24/7",
      companionDemo1: "Mình không hiểu sự khác biệt giữa nguyên phân và giảm phân. Bạn có thể giúp không?",
      companionDemo2: "Câu hỏi hay đấy! Hãy nghĩ theo cách này: cả hai đều liên quan đến sự phân chia tế bào, nhưng chúng có mục tiêu khác nhau. Để mình gợi ý nhé—mỗi quá trình tạo ra bao nhiêu tế bào con?",
      companionDemo3: "Nguyên phân tạo ra 2 và giảm phân tạo ra 4 phải không?",
      companionDemo4: "Chính xác luôn! Bây giờ bạn đã hiểu rồi đấy. Đó là một điểm khác biệt then chốt cần nhớ cho kỳ thi của bạn.",
      whatWeValue: "Giá trị của chúng tôi",
      valuesTitle: "Các nguyên tắc đằng sau Prepetual",
      valuesSubtitle: "Đây không phải là những giá trị doanh nghiệp trên tường. Đó là những niềm tin đã định hình mọi quyết định trong việc xây dựng công cụ này.",
      valueTitle1: "Tiếp cận cho tất cả",
      valueDesc1: "Các công cụ giáo dục nên miễn phí và có sẵn cho mọi học sinh, ở mọi nơi. Không ngoại lệ. Không có các gói cao cấp. Nếu bạn có thể truy cập internet, bạn có thể sử dụng Prepetual.",
      valueTitle2: "Sự thấu hiểu là trên hết",
      valueDesc2: "Mọi tính năng đều được thiết kế để làm sâu sắc thêm sự thấu hiểu, không chỉ giúp bạn vượt qua một bài kiểm tra. Bởi vì một học sinh hiểu rõ kiến thức sẽ không cần lo lắng về kỳ thi.",
      valueTitle3: "Quyền riêng tư quan trọng",
      valueDesc3: "Dữ liệu học tập của bạn thuộc về bạn. Chúng tôi không bán, chia sẻ hay sử dụng nó cho bất kỳ mục đích nào khác ngoài việc giúp bạn học. Ghi chú của bạn vẫn là của bạn.",
      valueTitle4: "Luôn cải tiến",
      valueDesc4: "Chúng tôi nghiên cứu khoa học về học tập, lắng nghe học sinh và không ngừng phát triển Prepetual. Mục tiêu của chúng tôi luôn nhất quán: giúp bạn hiểu nhiều hơn, nhanh hơn.",
      acrossEverySubject: "Trên mọi môn học",
      approachTitle: "Cách tiếp cận của chúng tôi với các môn học khác nhau",
      approachDesc: "Sự thấu hiểu biểu hiện khác nhau ở mỗi môn học. Đây là cách Prepetual áp dụng triết lý chung của chúng tôi—thấu hiểu thay vì ghi nhớ—trên các chủ đề bạn học.",
      howItWorks: "Cách hoạt động trong thực tế",
      subjects: {
        Math: {
          title: "Toán học",
          philosophy: "Toán học không phải là việc ghi nhớ các công thức—mà là hiểu tại sao chúng hoạt động. Khi chúng ta thực sự nắm vững logic đằng sau một công thức, chúng ta có thể tự suy luận ra nó, áp dụng nó vào các vấn đề mới và không bao giờ cảm thấy lạc lõng trong kỳ thi. Prepetual tạo ra các câu hỏi kiểm tra khả năng lập luận của bạn, không chỉ là khả năng thay số vào công thức.",
          example: "Thay vì hỏi \"Công thức bậc hai là gì?\", Prepetual có thể hỏi \"Tại sao phương pháp bình phương một tổng dẫn đến công thức bậc hai?\" hoặc đưa ra một vấn đề yêu cầu bạn quyết định nên sử dụng cách tiếp cận nào.",
        },
        EnglishLiterature: {
          title: "Tiếng Anh & Văn học",
          philosophy: "Văn học là về sự diễn giải, ngữ cảnh và kết nối các ý tưởng qua các văn bản. Việc ghi nhớ các bản tóm tắt cốt truyện sẽ không giúp bạn viết được một bài luận tốt. Chúng tôi tin vào việc kiểm tra khả năng phân tích chủ đề, hiểu động cơ nhân vật và hình thành các lập luận của riêng bạn dựa trên bằng chứng từ văn bản.",
          example: "Thay vì \"Nhân vật chính của cuốn tiểu thuyết là ai?\", bạn có thể thấy \"Tác giả sử dụng bối cảnh như thế nào để phản ánh xung đột nội tâm của nhân vật chính?\" Những câu hỏi thúc đẩy bạn suy nghĩ chín chắn.",
        },
        Science: {
          title: "Khoa học",
          philosophy: "Khoa học được xây dựng trên việc hiểu các quá trình, không phải ghi nhớ các sự kiện. Nếu bạn hiểu cách quang hợp hoạt động ở cấp độ khái niệm, bạn có thể trả lời bất kỳ câu hỏi nào về nó—ngay cả những câu hỏi bạn chưa từng thấy trước đây. Đó là sức mạnh của sự thấu hiểu so với việc ghi nhớ.",
          example: "Thay vì \"Nêu tên các giai đoạn của quá trình nguyên phân,\" Prepetual hỏi \"Điều gì sẽ xảy ra với một tế bào nếu các thoi vô sắc không hình thành trong quá trình nguyên phân?\" Hiểu quá trình có nghĩa là bạn có thể dự đoán kết quả.",
        },
        SocialStudiesHistory: {
          title: "Khoa học xã hội & Lịch sử",
          philosophy: "Lịch sử không phải là một danh sách các ngày tháng và tên gọi—nó là về việc hiểu nguyên nhân và kết quả, nhận ra các khuôn mẫu và học hỏi từ các quyết định của con người. Khi bạn hiểu tại sao các sự kiện xảy ra, bạn có thể kết nối chúng với các sự kiện khác và nhìn thấy bức tranh toàn cảnh hơn.",
          example: "Không phải là \"Chiến tranh thế giới thứ nhất bắt đầu vào năm nào?\" mà là \"Sự kết hợp của các liên minh và căng thẳng nào đã khiến một cuộc xung đột quy mô lớn ở châu Âu gần như là không thể tránh khỏi vào năm 1914?\" Hiểu ngữ cảnh giúp các sự kiện được ghi nhớ một cách tự nhiên.",
        },
        GlobalLanguages: {
          title: "Ngôn ngữ thế giới",
          philosophy: "Học một ngôn ngữ là về việc hiểu cách nó vận hành—các cấu trúc ngữ pháp, cấu trúc câu, ngữ cảnh—chứ không chỉ là ghi nhớ danh sách từ vựng. Khi chúng ta hiểu các quy tắc, chúng ta có thể đặt những câu mà chúng ta chưa bao giờ luyện tập trước đây và giao tiếp một cách tự do.",
          example: "Ngoài việc \"Dịch từ này,\" Prepetual kiểm tra xem bạn có thể sử dụng từ đó đúng ngữ cảnh hay không, hiểu tại sao một thì nhất định được sử dụng hoặc nhận ra sắc thái giữa các biểu đạt tương tự.",
        },
        OtherSubjects: {
          title: "Các môn học khác",
          philosophy: "Bất kể môn học nào—nghệ thuật, âm nhạc, khoa học máy tính, tâm lý học—nguyên tắc tương tự vẫn được áp dụng. Việc ghi nhớ bề mặt sẽ phai nhạt nhanh chóng. Nhưng khi bạn xây dựng được một mô hình tư duy về cách một thứ gì đó hoạt động, kiến thức đó sẽ trở thành một phần trong cách bạn suy nghĩ. Đó là điều Prepetual hướng tới, trong mọi môn học.",
          example: "Tải lên bất kỳ tài liệu học tập nào và AI sẽ thích nghi. Nó nhận diện môn học, hiểu nội dung và tạo ra các câu hỏi thử thách khả năng lĩnh hội của bạn—chứ không phải trí nhớ ngắn hạn của bạn.",
        },
      },
    },
    learningTips: [
      "Lặp lại ngắt quãng giúp bạn nhớ tốt hơn. Hãy thử xem lại các bài quiz sau những khoảng thời gian tăng dần để đạt được khả năng ghi nhớ tối đa.",
      "Dạy cho người khác những gì bạn đã học là một trong những cách tốt nhất để củng cố sự hiểu biết của chính bạn.",
      "Nghỉ giải lao giữa các buổi học giúp não bộ của bạn củng cố thông tin hiệu quả hơn.",
      "Gợi nhớ chủ động (tự kiểm tra bản thân) hiệu quả hơn là ôn tập thụ động. Hãy tiếp tục làm các bài quiz đó nhé!",
      "Ngủ đủ giấc là rất quan trọng để củng cố trí nhớ. Não của bạn sẽ xử lý những gì bạn đã học trong khi bạn nghỉ ngơi.",
      "Kết hợp các chủ đề khác nhau trong các buổi học. Việc học xen kẽ các môn học có thể cải thiện khả năng ghi nhớ dài hạn.",
      "Viết lại các khái niệm chính bằng tay. Hành động viết giúp gắn chặt thông tin vào trí nhớ.",
      "Tạo các liên tưởng tinh thần hoặc câu chuyện để kết nối thông tin mới với những gì bạn đã biết.",
      "Học trong các đợt tập trung ngắn từ 25-30 phút, sau đó nghỉ giải lao 5 phút. Đây gọi là kỹ thuật Pomodoro.",
      "Thử thách bản thân với những câu hỏi khó hơn. Gặp khó khăn một chút giúp bạn học sâu hơn.",
      "Ôn lại tài liệu ngay trước khi ngủ. Não của bạn sẽ tiếp tục xử lý nó suốt đêm.",
      "Giải thích các khái niệm bằng ngôn từ của riêng bạn. Nếu bạn không thể đơn giản hóa nó, nghĩa là bạn chưa hiểu nó đủ sâu.",
      "Cung cấp đủ nước và duy trì chế độ dinh dưỡng tốt. Não của bạn cần nhiên liệu phù hợp để học tập hiệu quả.",
      "Tự kiểm tra trước khi bạn nghĩ rằng mình đã sẵn sàng. Mắc lỗi sớm giúp xác định lỗ hổng kiến thức.",
      "Kết nối các khái niệm mới với các ví dụ thực tế. Các ứng dụng thực tế làm cho các ý tưởng trừu tượng trở nên dễ nhớ hơn.",
      "Khi làm các câu hỏi trắc nghiệm, đừng chỉ tìm đáp án đúng. Hãy tự giải thích tại sao ba lựa chọn còn lại là sai. Điều này giúp tăng gấp ba lần hiệu quả học tập từ một câu hỏi duy nhất.",
      "Tải tài liệu lên và làm quiz trước khi bắt đầu học chuyên sâu. Bài 'kiểm tra trước' này làm nổi bật chính xác phần nào trong tài liệu bạn đã biết và phần nào cần sự chú ý tối đa.",
    ],
    home: {
      hero: {
        makeYourMaterials: "Để tài liệu của bạn",
        talkBack: "biết lên tiếng",
        subtitle: "Hãy để mọi định nghĩa phản hồi bạn. Luôn kết nối với những gì bạn học.",
        getStarted: "Bắt đầu ngay",
        itsFree: "—miễn phí",
        howItWorks: "Cách hoạt động",
        freeForever: "Miễn phí mãi mãi",
        noCreditCard: "Không cần thẻ",
        fileFormats: "PDF, Word, Ảnh",
      },
      stats: {
        freeForever: "Miễn phí mãi mãi",
        fileFormats: "Định dạng tệp",
        unlimitedQuizzes: "Không giới hạn Quiz",
      },
      howItWorks: {
        badge: "Quy trình đơn giản",
        title: "Cách hoạt động",
        subtitle: "Từ ghi chú đến quiz chỉ trong vài cú nhấp chuột",
        steps: {
          upload: {
            title: "Bước 1: Tải lên",
            label: "Tải lên",
            desc: "Thả tài liệu học tập của bạn — PDF, ảnh, Word hoặc PowerPoint. Chúng tôi lo phần còn lại.",
            clickToUpload: "Nhấp để tải lên",
            orDragDrop: "hoặc kéo và thả tệp",
          },
          extract: {
            title: "Bước 2: Trích xuất",
            label: "Trích xuất",
            desc: "AI của chúng tôi đọc và hiểu nội dung của bạn với độ chính xác cao — bao gồm văn bản, biểu đồ và bảng biểu.",
            parsing: "Đang phân tích tài liệu...",
            extracting: "Đang trích xuất các khái niệm...",
            identifying: "Đang xác định các mối quan hệ...",
            complete: "hoàn tất",
            advanced: "Trích xuất nâng cao",
            fidelity: "Phân tích độ trung thực cao không bỏ sót",
          },
          generate: {
            title: "Bước 3: Tạo Quiz",
            label: "Tạo Quiz",
            desc: "AI thông minh tạo ra các câu hỏi quiz đa dạng, cá nhân hóa từ tài liệu của bạn — ngay lập tức.",
            mcq: "Trắc nghiệm",
            tf: "Đúng / Sai",
            short: "Trả lời ngắn",
            q1: "Chức năng chính của ty thể là gì?",
            q2: "Sự nhân đôi DNA xảy ra ở pha G1.",
            q3: "Định nghĩa thuật ngữ 'Thẩm thấu' theo cách của bạn.",
            architecting: "AI đang thiết lập...",
          },
          learn: {
            title: "Bước 4: Học tập",
            label: "Học tập",
            desc: "Nắm vững mọi chủ đề với các bài quiz tương tác, flashcard và lặp lại ngắt quãng.",
            expert: "Trình độ Chuyên gia",
            mastery: "Tiến trình thông thạo",
            fastTracking: "Đang tiến triển nhanh",
            startQuiz: "Bắt đầu Quiz",
            study: "Học tập",
          },
        },
      },
      parsing: {
        badge: "Nhập câu hỏi của riêng bạn",
        title: "Ngữ cảnh của bạn, chính xác như nó vốn có.",
        subtitle: "Tải lên bất kỳ bài kiểm tra hay bảng bài tập nào. Chúng tôi trích xuất thông minh từng câu hỏi, từng chữ một.",
        original: "Tài liệu gốc",
        interactive: "Quiz tương tác",
        converting: "Đang chuyển đổi...",
        ready: "Sẵn sàng",
      },
      features: {
        badge: "Mọi thứ bạn cần",
        title: "Khai phá tiềm năng với AI",
        subtitle: "Từ ghi chú thô đến các buổi học tương tác chỉ trong vài giây.",
        createFirstQuiz: "Tạo bài Quiz đầu tiên",
        dropNotes: "Thả ghi chú hoặc một trang sách giáo khoa để bắt đầu.",
        continueToGenerate: "Tiếp tục để tạo Quiz",
        startHere: "Bắt đầu tại đây",
        aiGen: {
          title: "Tạo Quiz bằng AI",
          desc: "AI của chúng tôi phân tích nội dung để tạo ra các loại câu hỏi đa dạng kiểm tra sự thấu hiểu.",
        },
        multiFormat: {
          title: "Hỗ trợ đa định dạng",
          desc: "PDF, ảnh sách giáo khoa, tệp Word và hình ảnh.",
        },
        progress: {
          title: "Theo dõi tiến độ",
          desc: "Cái nhìn trực quan về hành trình học tập của bạn.",
        },
        studyMode: {
          title: "Chế độ học thông minh",
          desc: "Flashcard tương tác thích ứng với bạn.",
        },
        pip: {
          title: "Gặp gỡ Pip, Bạn học AI",
          desc: "Pip đưa ra gợi ý và giải thích các khái niệm khi bạn gặp khó khăn.",
        },
        spaced: {
          title: "Lặp lại ngắt quãng",
          desc: "Thử lại các câu hỏi sai cho đến khi bạn nắm vững chúng.",
        },
      },
      cta: {
        badge: "Bắt đầu hành trình của bạn ngay hôm nay",
        title1: "Nắm vững tài liệu của bạn.",
        title2: "Nâng cao thành tích học tập.",
        desc: "Tham gia cùng hàng ngàn học sinh đã thay đổi cách học với các bài thực hành cá nhân hóa từ AI.",
        getStartedFree: "Bắt đầu miễn phí",
        learnMore: "Tìm hiểu thêm",
      },
      demo: {
        mitochondriaQ: "Chức năng chính của ty thể trong tế bào là gì?",
        energyProduction: "Sản xuất năng lượng",
        proteinSynthesis: "Tổng hợp protein",
        cellDivision: "Phân chia tế bào",
        wasteRemoval: "Loại bỏ chất thải",
        correct: "Chính xác!",
        mitochondriaExp: "Ty thể được biết đến là nhà máy năng lượng của tế bào, sản xuất ATP thông qua quá trình hô hấp tế bào.",
        revealHint: "Nhấn và giữ để hiển thị",
      },
    },
    dashboard: {
      welcomeBack: "Chào mừng bạn trở lại",
      learningDashboard: "Bảng điều khiển học tập",
      continueWhereLeftOff: "Tiếp tục nơi bạn đã dừng lại hoặc tạo nội dung mới.",
      createFirstQuiz: "Hãy tạo bài quiz đầu tiên và bắt đầu học thôi.",
      continueLearning: "Tiếp tục học tập",
      viewAllInProgress: "Xem tất cả đang làm",
      recentQuizzes: "Bài quiz gần đây",
      viewAll: "Xem tất cả",
      yourStats: "Thống kê của bạn",
      created: "ĐÃ TẠO",
      questions: "CÂU HỎI",
      accuracy: "ĐỘ CHÍNH XÁC",
      quickActions: "Thao tác nhanh",
      createNewQuiz: "Tạo quiz mới",
      aiPoweredGeneration: "Tạo bằng AI",
      continueStudy: "Tiếp tục học",
      learningTip: "Mẹo học tập",
      deleteQuizProgress: "Xóa tiến trình bài quiz?",
      revisingWarning: "Bạn đang ôn tập bài quiz này. Việc xóa sẽ gỡ bỏ toàn bộ tiến trình bao gồm câu trả lời ban đầu và tiến trình ôn tập.",
      keepRevising: "Tiếp tục ôn tập",
      deleteAllProgress: "Xóa toàn bộ tiến trình",
    },
    create: {
      title: "Tạo bài Quiz thực hành",
      subtitle: "Hôm nay bạn muốn thêm tài liệu học tập bằng cách nào?",
      uploadDocs: "Tải tài liệu lên",
      uploadDocsDesc: "Tải lên PDF, ghi chú trên lớp hoặc ảnh chụp sách giáo khoa",
      pasteNotes: "Dán ghi chú học tập",
      pasteNotesDesc: "Sao chép và dán ghi chú kỹ thuật số hoặc bản tóm tắt của bạn",
      learnYoutube: "Học từ YouTube",
      learnYoutubeDesc: "Biến bất kỳ video giáo dục nào thành bài kiểm tra thực hành",
      materialReady: "Tài liệu học tập đã sẵn sàng",
      pagesAdded: "đã thêm {count} trang và sẵn sàng để Pip kiểm tra",
      wordsAdded: "Đã thêm {count} từ từ {source} của bạn",
      removeMaterial: "Xóa tài liệu học tập?",
      removeMaterialDesc: "Thao tác này sẽ xóa các ghi chú hiện tại của bạn. Bạn sẽ cần tải lên hoặc dán lại để tiếp tục.",
      confirmRemoval: "Xác nhận xóa",
      formats: {
        docs: "PDF / DOCX",
        photos: "Ảnh chụp ghi chép",
        handwritten: "Ghi chép tay",
        summaries: "Bản tóm tắt",
        lectures: "Bài giảng video",
        explainers: "Video giải thích",
      },
      wordsCount: "{count} Từ",
      visualAssetsFound: "Đã tìm thấy nội dung hình ảnh",
      preview: "Xem trước",
      generateQuestions: "Tạo câu hỏi",
      addStudyMaterials: "Thêm tài liệu học tập",
      fileSizeLimit: "Dung lượng tệp lên đến 10MB",
      pastePlaceholder: "Dán tài liệu học tập của bạn vào đây... (AI hoạt động tốt nhất với chi tiết, vui lòng cung cấp ít nhất 50 ký tự)",
      readyToQuiz: "Sẵn sàng làm Quiz",
      validationError: "Nội dung chi tiết hơn sẽ mang lại bài quiz chất lượng hơn. Vui lòng cung cấp ít nhất 50 ký tự.",
      youtubeLink: "Thả liên kết YouTube vào bên dưới và chúng tôi sẽ trích xuất kiến thức cốt lõi cho bài quiz của bạn.",
      youtubePlaceholder: "https://www.youtube.com/watch?v=...",
      learningFromVideo: "Đang học từ video...",
      prepareQuiz: "Chuẩn bị Quiz",
      compatibility: "Tương thích: Liên kết Watch hoặc Short",
      youtubeVideo: "video YouTube",
      pastedText: "văn bản đã dán",
      image: "hình ảnh",
      document: "tài liệu",
    },
    feed: {
      discover: "Khám phá",
      exploreCommunity: "Khám phá các bài quiz được chia sẻ bởi cộng đồng prepetual",
      searchQuizzes: "Tìm kiếm bài quiz...",
      totalQuizzes: "bài quiz",
      totalQuestions: "câu hỏi",
      totalCreators: "người tạo",
      recommendedForYou: "Gợi ý cho bạn",
      basedOnHistory: "Dựa trên lịch sử học tập của bạn",
      noQuizzesFound: "Không tìm thấy bài quiz nào",
      tryDifferentSearch: "Hãy thử một từ khóa tìm kiếm khác",
      clearFilters: "Xóa bộ lọc",
      noQuizzesYet: "Chưa có bài quiz nào",
      beFirstToShare: "Hãy là người đầu tiên chia sẻ kiến thức của bạn với cộng đồng!",
      featured: "Nổi bật",
      popularQuizzes: "Các bài quiz phổ biến từ cộng đồng",
      allQuizzes: "Tất cả bài quiz",
      recentQuizzes: "Bài quiz gần đây",
      moreQuizzesToExplore: "còn {count} bài quiz khác để khám phá",
      quizzesAvailable: "có {count} bài quiz",
      play: "Chơi",
      takeQuiz: "Làm Quiz",
      study: "Học tập",
      curated: "Được chọn lọc",
      forYou: "Dành cho bạn",
      practiceMore: "Luyện tập thêm",
      quizCreator: "Người tạo Quiz",
    },
    history: {
      title: "Thư viện",
      savedQuizzes: "Đã lưu {count} bài quiz",
      savedQuiz: "Đã lưu {count} bài quiz",
      noQuizzesSaved: "Các bài quiz đã lưu sẽ xuất hiện ở đây",
      newQuiz: "Quiz mới",
      quizzes: "Bài quiz",
      folders: "Thư mục",
      noQuizzesYet: "Chưa có bài quiz nào",
      createFirstQuiz: "Hãy tạo bài quiz đầu tiên để bắt đầu",
      createQuiz: "Tạo Quiz",
      searchLibrary: "Tìm kiếm trong thư viện...",
      allSubjects: "Tất cả môn học",
      noMatchingQuizzes: "Không tìm thấy bài quiz nào phù hợp trong thư viện.",
      clearFilters: "Xóa tất cả bộ lọc",
      questions: "{count} câu hỏi",
      review: "Ôn tập",
      take: "Làm",
      editQuiz: "Chỉnh sửa Quiz",
      draftMode: "Chế độ nháp",
      publishToLibrary: "Công khai lên Thư viện",
      copyShareLink: "Sao chép liên kết chia sẻ",
      permanentlyDelete: "Xóa vĩnh viễn",
      collectionManager: "Quản lý bộ sưu tập",
      organizeDesc: "Sắp xếp thư viện thực hành cá nhân của bạn theo môn học.",
      createFolder: "Tạo thư mục",
      stayOrganized: "Giữ ngăn nắp",
      groupQuizzesDesc: "Nhóm các bài quiz của bạn theo lớp, kỳ thi hoặc chủ đề để truy cập nhanh hơn.",
      quiz: "bài quiz",
      quizzesCount: "bài quiz",
      unpinFromTop: "Bỏ ghim khỏi đầu",
      pinToTop: "Ghim lên đầu",
      renameFolder: "Đổi tên thư mục",
      deleteCollection: "Xóa bộ sưu tập",
      deleteQuiz: "Xóa Quiz",
      deleteQuizConfirm: "Bạn có chắc chắn muốn xóa \"{title}\"? Hành động này không thể hoàn tác.",
      deleteFolderConfirm: "Bạn có chắc chắn muốn xóa \"{name}\"? Các bài quiz bên trong sẽ không bị xóa, chúng chỉ trở thành không nằm trong thư mục nào.",
      archive: "Lưu trữ",
      addQuizzes: "Thêm bài quiz",
      folderNotFound: "Không tìm thấy thư mục",
      folderNotFoundDesc: "Thư mục này có thể đã bị xóa.",
      backToArchive: "Quay lại Lưu trữ",
      removeFromFolder: "Xóa khỏi thư mục",
      noQuizzesInFolderDesc: "Thêm các bài quiz hiện có hoặc tạo mới để sắp xếp tại đây",
      addQuizzesToFolder: "Thêm bài quiz vào thư mục",
      selectQuizzesForFolder: "Chọn các bài quiz để đưa vào \"{name}\"",
      quizzesUpdated: "Đã cập nhật các bài quiz",
      quizRemovedFromFolder: "Đã xóa bài quiz khỏi thư mục",
      failedToRemoveQuiz: "Xóa bài quiz thất bại",
      rename: "Đổi tên",
      save: "Lưu",
      questionsCount: "{count} câu hỏi",
      quizDeleted: "Đã xóa bài quiz",
      quizDeletedDesc: "Bài quiz đã được xóa khỏi lịch sử của bạn.",
      error: "Lỗi",
      failedDeleteQuiz: "Xóa bài quiz thất bại",
      quizShared: "Đã chia sẻ bài quiz",
      quizHidden: "Đã ẩn bài quiz",
      quizSharedDesc: "Bài quiz của bạn hiện đã hiển thị trong cộng đồng.",
      quizHiddenDesc: "Bài quiz của bạn hiện đã được đặt ở chế độ riêng tư.",
      failedUpdateVisibility: "Cập nhật chế độ hiển thị thất bại",
      folderCreated: "Đã tạo thư mục",
      failedCreateFolder: "Tạo thư mục thất bại",
      folderRenamed: "Đã đổi tên thư mục",
      failedRenameFolder: "Đổi tên thư mục thất bại",
      folderDeleted: "Đã xóa thư mục",
      failedDeleteFolder: "Xóa thư mục thất bại",
      failedTogglePin: "Thay đổi ghim thất bại",
      linkCopied: "Đã sao chép liên kết!",
      linkCopiedDesc: "Chia sẻ liên kết này với người khác để họ có thể làm bài quiz.",
    },
    inProgress: {
      title: "Đang làm",
      loadingSessions: "Đang tải các phiên đã lưu...",
      loadingProgress: "Đang tải các phiên đã lưu...",
      sessionsWaiting: "có {count} phiên làm quiz đang chờ hoàn thành",
      sessionWaiting: "có {count} phiên làm quiz đang chờ hoàn thành",
      allCaughtUpDesc: "Đã hoàn thành tất cả — không có phiên nào đang làm",
      allCaughtUp: "Đã hoàn thành tất cả — không có phiên nào đang làm",
      sessionsCount: "{count} phiên",
      sessionCount: "{count} phiên",
      loadingProgressEllipsis: "Đang tải tiến trình...",
      allCaughtUpTitle: "Đã hoàn thành tất cả!",
      noInProgressDesc: "Bạn không có bài quiz nào đang làm. Hãy bắt đầu một bài quiz và lưu tiến trình để tiếp tục sau.",
      browseQuizzes: "Duyệt các bài quiz",
      revising: "Đang ôn tập",
      questionsLeftToReview: "còn {count} câu hỏi cần xem lại",
      questionLeftToReview: "còn {count} câu hỏi cần xem lại",
      answeredOfTotal: "Đã trả lời {answered}/{total}",
      questionsTotal: "tổng cộng {count} câu hỏi",
      continueReview: "Tiếp tục ôn tập",
      continueQuiz: "Tiếp tục làm quiz",
      discardProgress: "Hủy bỏ tiến trình?",
      discardRevisionDesc: "Thao tác này sẽ xóa vĩnh viễn toàn bộ tiến trình cho \"{title}\", bao gồm câu trả lời ban đầu và tiến trình ôn tập.",
      discardProgressRevisingDesc: "Thao tác này sẽ xóa vĩnh viễn toàn bộ tiến trình cho \"{title}\", bao gồm câu trả lời ban đầu và tiến trình ôn tập.",
      discardProgressDesc: "Thao tác này sẽ hủy bỏ tiến trình đã lưu cho \"{title}\". Bạn có thể làm lại từ đầu.",
      keepIt: "Giữ lại",
      discard: "Hủy bỏ",
      spent: "đã học {time}",
      timeSpent: "đã học {time}",
      ago: "{time} trước",
    },
    study: {
      noQuizSelected: "Chưa chọn bài quiz",
      noQuizSelectedDesc: "Chọn một bài quiz từ lịch sử để bắt đầu ghi nhớ bằng flashcard.",
      goHistory: "Đi tới Thư viện",
      multipleChoice: "Trắc nghiệm",
      trueFalse: "Đúng / Sai",
      shortAnswer: "Trả lời ngắn",
      sessionComplete: "Hoàn thành phiên học!",
      sessionCompleteDesc: "Tiến bộ tuyệt vời với bài \"{title}\"",
      mastered: "Đã thành thạo",
      stillLearning: "Đang học",
      retakeCards: "Làm lại thẻ",
      returnDashboard: "Quay lại Bảng điều khiển",
      flashcardSession: "Phiên học Flashcard",
      progress: "Tiến độ: {current} / {total}",
      question: "Câu hỏi",
      tapToReveal: "Chạm để xem câu trả lời",
      correctAnswer: "Câu trả lời đúng",
      explanation: "Giải thích",
      swipeToGrade: "Vuốt sang trái hoặc phải để chấm điểm",
      learning: "Đang học",
      swipeArrowNav: "Vuốt hoặc dùng phím mũi tên để di chuyển",
    },
    results: {
      title: "Lịch sử kết quả",
      subtitle: "Xem lại tất cả các lượt làm quiz trước đây và theo dõi tiến độ của bạn.",
      totalAttempts: "Tổng cộng {count} lượt làm",
      noResultsYet: "Chưa có kết quả",
      noResultsDesc: "Hãy làm bài quiz đầu tiên để xem kết quả và lịch sử chi tiết tại đây.",
      createQuiz: "Tạo bài Quiz",
      searchPlaceholder: "Tìm kiếm bài quiz theo tiêu đề...",
      allSubjects: "Tất cả môn học",
      noResultsMatching: "Không tìm thấy kết quả phù hợp với bộ lọc.",
      clearFilters: "Xóa tất cả bộ lọc",
      revisionAvailable: "Có thể ôn tập",
      correct: "đúng",
      attempts: "{count} lượt làm",
      best: "Tốt nhất: {score}%",
      revise: "Ôn tập",
      bestLabel: "Tốt nhất",
      correctCount: "{correct}/{total} câu đúng",
      attemptsCount: "{count} lượt làm",
      smartReviewGenerated: "Đã tạo ôn tập thông minh",
      smartReviewDesc: "Tập trung vào các lỗi sai thường xuyên nhất và các thử thách tương tự.",
      reviewFailed: "Tạo ôn tập thất bại",
      reviewFailedDesc: "Không thể tạo phiên ôn tập. Vui lòng thử lại.",
    },
    quizResults: {
      scoreMessages: {
        90: "Xuất sắc — bạn đang rất vững.",
        80: "Rất tốt — chỉ còn một chút nữa!",
        70: "Tiến bộ tốt — hãy tiếp tục luyện tập.",
        60: "Khởi đầu ổn — xem lại và thử lại nhé.",
        default: "Cố lên — luyện tập sẽ giúp bạn tiến bộ.",
      },
      quizSessionSummary: "{correct}/{total} đúng",
      reviewSessionSummary: "Sửa đúng {correct}/{total} trong phiên ôn",
      fixed: "Đã sửa",
      needsWork: "Cần ôn thêm",
      reviewAnswers: "Xem lại câu trả lời",
      yourAnswer: "Câu trả lời của bạn",
      noAnswerProvided: "Chưa trả lời",
      correctAnswer: "Đáp án đúng",
      whyThisWasWrong: "Vì sao sai",
      signUpToSeeExplanations: "Đăng nhập để xem giải thích chi tiết.",
      unlockFullFeatures: "Mở khoá tính năng",
      unlockFullFeaturesDesc: "Tạo tài khoản để lưu kết quả, theo dõi tiến độ và ôn tập thông minh hơn.",
      alreadyHaveAccount: "Đã có tài khoản?",
      retakeQuiz: "Làm lại quiz",
    },
    quizComplete: {
      quizComplete: "Hoàn thành quiz!",
      quizCompleteDesc: "Làm tốt lắm — đây là kết quả của bạn.",
      reviewSessionComplete: "Hoàn thành phiên ôn!",
      reviewSessionCompleteDesc: "Rất tốt — đây là kết quả của bạn.",
    },
    revisionSummary: {
      greatPractice: "Luyện tập tuyệt vời!",
      buildingMemories: "Bạn đang củng cố trí nhớ mạnh mẽ hơn với mỗi lần ôn tập.",
      questionsMastered: "câu đã nắm vững trong phiên này",
      retryCount: "trong đó có {count} câu bạn đã làm đúng khi thử lại",
      weeklyRevisedCount: "câu đã ôn tập trong tuần này",
      mistakesLockDesc: "Sai lầm là cách trí nhớ được khắc sâu. Hãy tiếp tục ôn luyện và bạn sẽ thấy chúng biến mất.",
    },
    generate: {
      goBack: "Quay lại",
      materialProcessed: "Tài liệu đã xử lý & Sẵn sàng",
      title: "Tùy chỉnh bài luyện tập",
      subtitle: "Thiết lập sở thích của bạn và để Prepetual xây dựng bài quiz hoàn hảo.",
    },
    quiz: {
      back: "Quay lại",
    },
    quizGenerator: {
      yourStudyMaterial: "Tài liệu học tập của bạn",
      imagesReady: "{count} hình ảnh đã sẵn sàng để AI phân tích",
      imageReady: "{count} hình ảnh đã sẵn sàng để AI phân tích",
      clickToInspect: "Nhấn để kiểm tra các trang",
      viewExtractedText: "Xem văn bản đã trích xuất",
      charactersReady: "{count} ký tự đã sẵn sàng để tạo quiz",
      collapse: "Thu gọn",
      expandFullText: "Xem toàn bộ văn bản",
      viewImages: "Xem hình ảnh",
      smartPractice: "Luyện tập thông minh",
      smartPracticeDesc: "Prepetual tạo các câu hỏi gốc dựa trên ghi chú cụ thể của bạn.",
      importQuestions: "Nhập câu hỏi",
      importQuestionsDesc: "Bạn đã có sẵn bài kiểm tra? Prepetual có thể quét và tìm câu trả lời.",
      numQuestions: "Số lượng câu hỏi",
      chooseQuestions: "Chọn từ 3-{max} câu hỏi",
      difficultyLevel: "Mức độ khó",
      howChallenging: "Bài quiz nên thử thách đến mức nào?",
      easy: "Dễ",
      medium: "Trung bình",
      hard: "Khó",
      questionTypes: "Loại câu hỏi",
      selectOneOrMore: "Chọn một hoặc nhiều loại",
      multipleChoice: "Trắc nghiệm",
      multipleChoiceDesc: "A, B, C hoặc D",
      trueFalse: "Đúng / Sai",
      true: "Đúng",
      false: "Sai",
      trueFalseDesc: "Đúng hoặc Sai",
      shortAnswer: "Trả lời ngắn",
      shortAnswerDesc: "Tự viết câu trả lời",
      preparePracticeQuiz: "Chuẩn bị bài Quiz thực hành",
      smartImport: "Nhập thông minh",
      smartImportDesc: "Đã có bài kiểm tra? Prepetual sẽ quét, nhận diện câu hỏi và xác minh đáp án cho bạn.",
      perfectFor: "Hoàn hảo cho",
      quizPapers: "Đề kiểm tra",
      worksheets: "Phiếu bài tập",
      importPracticeQuiz: "Nhập bài Quiz thực hành",
    },
    quizPlayer: {
      excellentWork: "Làm tốt lắm!",
      nailedIt: "Bạn đã làm được!",
      brilliant: "Tuyệt vời!",
      keepItUp: "Cố gắng phát huy!",
      perfect: "Hoàn hảo!",
      outstanding: "Xuất sắc!",
      onFire: "Bạn đang thăng hoa!",
      impressive: "Rất ấn tượng!",
      improvement: "Hãy xem sự tiến bộ này!",
      learnedLastOne: "Bạn đã học được từ câu trước! Tuyệt vời!",
      secondCharm: "Lần thứ hai là thành công! Làm tốt lắm!",
      masteredNow: "Giờ bạn đã thành thạo điều này rồi!",
      growthMindset: "Tư duy phát triển đang phát huy!",
      persistencePays: "Sự kiên trì đã được đền đáp! Làm tốt lắm!",
      didntGiveUp: "Bạn đã không bỏ cuộc và kết quả đã rõ!",
      howYouLearn: "Đó là cách bạn học hỏi! Thật tuyệt vời!",
      dontWorry: "Đừng lo lắng, hãy tiếp tục học nhé!",
      getNextOne: "Bạn sẽ làm được câu tiếp theo thôi!",
      learningInProgress: "Đang trong quá trình học hỏi!",
      everyMistake: "Mỗi sai lầm là một bài học!",
      stayCurious: "Hãy luôn tò mò nhé!",
      streak2: "2 câu liên tiếp!",
      streak3: "3 câu liên tiếp! Hay lắm!",
      streak4: "4 câu liên tiếp! Tuyệt vời!",
      streak5: "Chuỗi 5+! Không thể ngăn cản!",
      doingGreat: "Bạn đang làm rất tốt!",
      keepGoing: "Đừng lo, hãy tiếp tục nhé!",
      reportSubmitted: "Đã gửi báo cáo",
      reportSubmittedDesc: "Cảm ơn phản hồi của bạn! Chúng tôi sẽ xem xét câu hỏi này.",
      reportError: "Lỗi",
      reportErrorDesc: "Gửi báo cáo thất bại. Vui lòng thử lại sau.",
      multipleChoice: "Trắc nghiệm",
      trueFalse: "Đúng/Sai",
      shortAnswer: "Trả lời ngắn",
      question: "Câu hỏi",
      correctAnswer: "Câu trả lời đúng",
      explanation: "Giải thích",
      grade: "Chấm điểm",
      check: "Kiểm tra",
      next: "Tiếp theo",
      previous: "Quay lại",
      finish: "Hoàn thành",
      saveProgress: "Lưu tiến trình",
      reportBug: "Báo lỗi",
      grading: "Đang chấm điểm...",
      yourAnswer: "Câu trả lời của bạn",
      typeYourAnswer: "Nhập câu trả lời của bạn vào đây...",
      shortAnswerFallbackCorrect: "Câu trả lời của bạn khớp với đáp án mong đợi.",
      shortAnswerFallbackIncorrect: "Đáp án mong đợi là: {expected}",
      submitFailed: "Không thể gửi bài quiz. Vui lòng thử lại.",
      reportFailed: "Gửi báo cáo thất bại. Vui lòng thử lại sau.",
      imagesCount: "Hình ảnh {current}/{total}",
      questionNumber: "Câu hỏi {number}",
      partiallyCorrect: "Đúng một phần",
      aiAssessment: "Đánh giá bởi AI",
      viewExplanation: "Xem giải thích",
      explain: "Giải thích",
      shortAnswerPlaceholder: "Nhập câu trả lời của bạn vào đây...",
      gradingInProgress: "Pip đang chấm điểm câu trả lời của bạn...",
      gradingInProgressShort: "Đang chấm...",
      jumpToQuestion: "Chuyển đến câu hỏi",
      giveItAnotherTry: "Thử lại lần nữa nào!",
      somethingWrong: "Có lỗi gì sao?",
      reportProblem: "Báo cáo vấn đề",
      reportProblemDesc: "Có điều gì đó không ổn với câu hỏi này? Hãy cho chúng tôi biết để chúng tôi sửa chữa.",
      whatIsIssue: "Vấn đề là gì?",
      reportReasons: {
        correct_answer_is_wrong: "Câu trả lời đúng bị sai",
        explanation_is_incorrect: "Lời giải thích không chính xác",
        typo_or_formatting_issue: "Lỗi đánh máy hoặc định dạng",
        question_is_unclear: "Câu hỏi không rõ ràng",
        other: "Khác"
      },
      detailsOptional: "Chi tiết (tùy chọn)",
      describeProblem: "Mô tả chi tiết vấn đề...",
      submitting: "Đang gửi...",
      submitReport: "Gửi báo cáo",
      studyMaterial: "Tài liệu học tập",
      material: "Tài liệu",
      hideTimer: "Ẩn đồng hồ",
      showTimer: "Hiện đồng hồ",
      askPip: "Hỏi Pip",
      results: "Kết quả",
    }
  },
};

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  tArray: (key: string) => string[];
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function getNestedValue(source: Record<string, DictionaryValue>, path: string): DictionaryValue | undefined {
  const parts = path.split(".");
  let current: DictionaryValue | undefined = source;

  for (const part of parts) {
    if (!current || typeof current === "string" || Array.isArray(current)) return undefined;
    current = current[part];
  }

  return current;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("app-language");
    return stored === "vi" ? "vi" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("app-language", language);
    document.documentElement.lang = language === "vi" ? "vi" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string, params?: Record<string, string | number>) => {
      const translated = getNestedValue(dictionaries[language], key) ?? getNestedValue(dictionaries.en, key) ?? key;

      if (typeof translated !== "string") return String(translated);

      if (!params) {
        if (translated.includes("{") && typeof window !== "undefined") {
          console.warn(`[i18n] Missing params for key "${key}":`, translated);
        }
        return translated.replace(/\{[a-zA-Z0-9_]+\}/g, "").replace(/\s{2,}/g, " ").trim();
      }

      const interpolated = Object.entries(params).reduce(
        (result, [paramKey, paramValue]) => result.replaceAll(`{${paramKey}}`, String(paramValue)),
        translated,
      );

      if (interpolated.includes("{") && typeof window !== "undefined") {
        console.warn(`[i18n] Unresolved placeholders for key "${key}":`, { translated, params, interpolated });
      }

      return interpolated.replace(/\{[a-zA-Z0-9_]+\}/g, "").replace(/\s{2,}/g, " ").trim();
    };

    const tArray = (key: string): string[] => {
      const translated = getNestedValue(dictionaries[language], key) ?? getNestedValue(dictionaries.en, key);
      return Array.isArray(translated) ? translated : [];
    };

    return {
      language,
      setLanguage: setLanguageState,
      t,
      tArray,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
