import { motion } from "framer-motion";
import { ArrowLeft, FileText, CheckCircle, Scale, UserPlus, FileSignature, AlertCircle, Info, HelpCircle } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function TermsOfService() {
  const sections = [
    {
      id: "1",
      title: "Acceptance of Terms",
      icon: CheckCircle,
      content: "By accessing and using Prepetual (\"the Service\"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use this service."
    },
    {
      id: "2",
      title: "Description of Service",
      icon: Info,
      content: "Prepetual is an AI-powered quiz generation platform that allows users to upload study materials and generate interactive quizzes. The Service includes document processing, AI-based question generation, quiz taking, and result tracking features."
    },
    {
      id: "3",
      title: "User Accounts",
      icon: UserPlus,
      content: "To access certain features, you must register for an account. You agree to provide accurate information and safeguard your password. You are responsible for all activities that occur under your account."
    },
    {
      id: "4",
      title: "User Content",
      icon: FileSignature,
      content: "You retain ownership of content you upload. By uploading, you grant us a non-exclusive license to process and store your content solely to provide the Service. You must ensure you have the right to upload any content you submit."
    },
    {
      id: "5",
      title: "Acceptable Use",
      icon: AlertCircle,
      content: (
        <div className="space-y-4">
          <p>You agree not to:</p>
          <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <li className="flex items-center gap-2 p-3 rounded-lg bg-red-500/5 border border-red-500/10 text-sm">
              <div className="h-1.5 w-1.5 rounded-full bg-red-500" />
              Use for unlawful purposes
            </li>
            <li className="flex items-center gap-2 p-3 rounded-lg bg-red-500/5 border border-red-500/10 text-sm">
              <div className="h-1.5 w-1.5 rounded-full bg-red-500" />
              Infringe on IP rights
            </li>
            <li className="flex items-center gap-2 p-3 rounded-lg bg-red-500/5 border border-red-500/10 text-sm">
              <div className="h-1.5 w-1.5 rounded-full bg-red-500" />
              Gain unauthorized access
            </li>
            <li className="flex items-center gap-2 p-3 rounded-lg bg-red-500/5 border border-red-500/10 text-sm">
              <div className="h-1.5 w-1.5 rounded-full bg-red-500" />
              Disrupt servers or service
            </li>
          </ul>
        </div>
      )
    },
    {
      id: "6",
      title: "AI-Generated Content",
      icon: HelpCircle,
      content: "Quizzes are generated by AI based on your content. While we strive for accuracy, we do not guarantee generated questions are correct. Please verify important information independently."
    },
    {
      id: "7",
      title: "Limitation of Liability",
      icon: Scale,
      content: "In no event shall Prepetual or its affiliates be liable for any indirect, incidental, or consequential damages arising from your use of the service."
    }
  ];

  return (
    <div className="min-h-screen bg-background/50">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="flex flex-col items-center text-center mb-16">
            <Link href="/">
              <Button variant="ghost" size="sm" className="mb-8 rounded-full hover:bg-primary/10" data-testid="button-back-home">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>
            
            <div className="p-4 bg-primary/10 rounded-3xl mb-6">
              <FileText className="h-12 w-12 text-primary" />
            </div>
            <h1 className="text-5xl font-black text-foreground mb-4 tracking-tight">Terms of Service</h1>
            <p className="text-xl text-muted-foreground max-w-2xl">
              Please read these terms carefully before using our platform.
            </p>
            <div className="mt-6 inline-flex items-center px-4 py-2 rounded-full bg-muted text-sm font-medium text-muted-foreground">
              Last updated: December 19, 2025
            </div>
          </div>

          <div className="grid grid-cols-1 gap-6 mb-16">
            {sections.map((section, idx) => (
              <motion.div
                key={section.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 * idx }}
              >
                <Card className="border-primary/5 shadow-sm overflow-hidden bg-card/50 backdrop-blur">
                  <CardContent className="p-8">
                    <div className="flex gap-6 items-start">
                      <div className="p-3 bg-primary/10 rounded-2xl text-primary flex-shrink-0 mt-1">
                        <section.icon className="h-6 w-6" />
                      </div>
                      <div className="space-y-3">
                        <h2 className="text-2xl font-bold text-foreground tracking-tight">
                          {section.id}. {section.title}
                        </h2>
                        <div className="text-muted-foreground leading-relaxed text-lg">
                          {section.content}
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>

          <div className="p-8 rounded-3xl bg-muted/30 border border-primary/5 text-center">
            <p className="text-muted-foreground">
              By using Prepetual, you agree to these terms. If you have questions, please reach out at{" "}
              <a href="mailto:support@prepetual.com" className="text-primary font-bold hover:underline underline-offset-4">
                support@prepetual.com
              </a>
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
