import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/lib/language-context";

export default function TermsOfService() {
  const { language } = useLanguage();

  const ui = language === "vi"
    ? {
        back: "Quay lại",
        title: "Điều khoản Dịch vụ",
        updated: "Cập nhật lần cuối: 2 tháng 5, 2026",
        sections: [
          {
            title: "1. Chấp nhận điều khoản",
            content: "Bằng việc truy cập và sử dụng Prepetual, bạn đồng ý tuân thủ các điều khoản này. Nếu bạn không đồng ý với bất kỳ phần nào của điều khoản, vui lòng ngừng sử dụng dịch vụ ngay lập tức."
          },
          {
            title: "2. Tài khoản người dùng",
            content: "Bạn có trách nhiệm bảo mật thông tin đăng nhập tài khoản của mình. Prepetual không chịu trách nhiệm cho bất kỳ tổn thất nào phát sinh từ việc bạn không bảo mật mật khẩu hoặc tài khoản."
          },
          {
            title: "3. Nội dung người dùng",
            content: "Bạn giữ quyền sở hữu đối với các tài liệu học tập tải lên. Tuy nhiên, bạn cấp cho chúng tôi quyền xử lý các nội dung này để tạo câu hỏi và hỗ trợ học tập thông qua AI."
          },
          {
            title: "4. Trợ lý AI và Nội dung tạo ra",
            content: "Nội dung do AI và trợ lý Prepal tạo ra chỉ mang tính chất tham khảo. Chúng tôi không cam kết độ chính xác tuyệt đối và khuyến khích người dùng kiểm chứng thông tin với các nguồn học liệu chính thống."
          },
          {
            title: "5. Hành vi bị nghiêm cấm",
            content: "Người dùng không được phép: (a) Sử dụng dịch vụ cho mục đích bất hợp pháp; (b) Can thiệp vào hạ tầng kỹ thuật; (c) Tải lên nội dung vi phạm bản quyền hoặc chứa mã độc."
          },
          {
            title: "6. Giới hạn trách nhiệm",
            content: "Prepetual được cung cấp trên cơ sở 'nguyên trạng'. Chúng tôi không chịu trách nhiệm cho bất kỳ thiệt hại trực tiếp hoặc gián tiếp nào phát sinh từ việc sử dụng hoặc không thể sử dụng dịch vụ."
          },
          {
            title: "7. Thay đổi điều khoản",
            content: "Chúng tôi có quyền cập nhật các điều khoản này bất kỳ lúc nào. Việc tiếp tục sử dụng dịch vụ sau khi có thay đổi đồng nghĩa với việc bạn chấp nhận các điều khoản mới."
          }
        ]
      }
    : {
        back: "Back",
        title: "Terms of Service",
        updated: "Last updated: May 2, 2026",
        sections: [
          {
            title: "1. Acceptance of Terms",
            content: "By accessing and using Prepetual, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the service."
          },
          {
            title: "2. User Accounts",
            content: "You are responsible for maintaining the confidentiality of your account and password. Prepetual shall not be liable for any loss resulting from your failure to comply with this security obligation."
          },
          {
            title: "3. User Content",
            content: "You retain ownership of the study materials you upload. By using the service, you grant us the necessary rights to process this content to generate AI-driven quizzes and study aids."
          },
          {
            title: "4. AI-Generated Content & Prepal",
            content: "Content generated by AI, including responses from Prepal, is provided for educational support only. We do not guarantee 100% accuracy and advise users to verify critical information independently."
          },
          {
            title: "5. Prohibited Conduct",
            content: "You agree not to: (a) Use the service for illegal purposes; (b) Interfere with the technical infrastructure; (c) Upload copyrighted material without permission or malicious code."
          },
          {
            title: "6. Limitation of Liability",
            content: "Prepetual is provided on an 'as-is' basis. In no event shall we be liable for any direct, indirect, or incidental damages arising from your use of the service."
          },
          {
            title: "7. Changes to Terms",
            content: "We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the revised Terms of Service."
          }
        ]
      };

  return (
    <div className="min-h-screen bg-background text-foreground font-['DM_Sans',sans-serif] transition-colors duration-300">
      <div className="container mx-auto max-w-3xl px-6 py-16">
        <motion.div 
          initial={{ opacity: 0 }} 
          animate={{ opacity: 1 }} 
          transition={{ duration: 0.4 }}
        >
          {/* Back Navigation */}
          <div className="mb-10 text-left">
            <Link href="/">
              <Button variant="ghost" className="p-1 h-auto text-muted-foreground hover:text-foreground">
                <ArrowLeft className="mr-2 h-4 w-4" />
                {ui.back}
              </Button>
            </Link>
          </div>

          {/* Header */}
          <header className="mb-12 border-b border-border pb-8">
            <h1 className="text-3xl font-bold tracking-tight mb-2">{ui.title}</h1>
            <p className="text-sm text-muted-foreground font-medium uppercase tracking-wider">{ui.updated}</p>
          </header>

          {/* Content Body */}
          <main className="space-y-12 text-left">
            {ui.sections.map((section) => (
              <section key={section.title} className="space-y-4">
                <h2 className="text-xl font-bold text-foreground">
                  {section.title}
                </h2>
                <div className="text-[1.05rem] leading-relaxed text-muted-foreground">
                  {section.content}
                </div>
              </section>
            ))}
          </main>

          {/* Footer */}
          <footer className="mt-24 border-t border-border pt-8 text-center text-sm text-muted-foreground">
            <p>© 2026 Prepetual. All rights reserved.</p>
            <p className="mt-2">Contact: giahienhn@gmail.com</p>
          </footer>
        </motion.div>
      </div>
    </div>
  );
}