import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Link href="/help">
            <Button variant="ghost" className="mb-8 group">
              <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
              Back to Help Center
            </Button>
          </Link>

          <div className="mb-12">
            <h1 className="text-4xl font-black mb-4 tracking-tight">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: December 19, 2025</p>
          </div>

          <div className="space-y-12 pb-12">
            {[
              { title: "1. Acceptance of Terms", content: "By accessing and using Prepetual, you agree to be bound by these terms. If you do not agree, please do not use the service." },
              { title: "2. Description of Service", content: "Prepetual is an AI-powered quiz generation platform for processing study materials and tracking learning progress." },
              { title: "3. User Accounts", content: "You are responsible for maintaining the confidentiality of your account and password. All activities under your account are your responsibility." },
              { title: "4. User Content", content: "You retain ownership of your uploaded content, but grant us a license to process and store it solely to provide our service." },
              { title: "5. Acceptable Use", content: "Users must not use the service for unlawful purposes, infringe intellectual property, or attempt to disrupt the platform." },
              { title: "6. AI-Generated Content", content: "Quizzes are generated by AI. While we strive for accuracy, we do not guarantee correctness and suggest verifying important facts." }
            ].map((section, i) => (
              <section key={i}>
                <h2 className="text-xl font-bold mb-4 text-foreground">{section.title}</h2>
                <p className="text-muted-foreground leading-relaxed">{section.content}</p>
              </section>
            ))}
          </div>
        </motion.div>
      </div>
    </div>
  );
}
